import type { BlogSection } from "./blog";
export const batchTwoAliases: Record<string,string> = {
  "apagon-abril-2025-un-ano-despues-que-cambio":"apagon-de-espana-de-2025-que-ha-cambiado-desde-entonces",
  "dana-diferencia-aviso-naranja-rojo-que-hacer":"dana-aviso-naranja-o-rojo-que-debes-hacer",
  "generador-electrico-casa-normativa-errores-peligrosos":"generador-en-casa-normativa-y-peligros-que-debes-evitar",
  "verano-2026-mas-caluroso-historia-espana-datos":"verano-de-2026-el-mas-calido-de-la-serie-en-espana",
  "kit-emergencia-coche-que-llevar":"kit-de-emergencia-para-el-coche-que-llevar-en-2026",
};
export const batchTwoRevisions: Record<string,{excerpt:string;sections:BlogSection[];relatedLinks:{label:string;href:string}[]}> = {
  "apagon-de-espana-de-2025-que-ha-cambiado-desde-entonces": {
    excerpt:"Más de un año después del apagón de abril de 2025: qué aporta el informe final, qué no demuestra una jornada institucional y cómo revisar lo aprendido en casa.",
    sections:[
      {heading:"Un año después: distinguir hechos de interpretaciones",body:"El apagón del 28 de abril de 2025 afectó a la España peninsular y Portugal continental. Revisar lo ocurrido exige separar tres preguntas: qué sucedió en la red, qué recomiendan los investigadores y qué necesita mejorar cada hogar. Este artículo trata del balance posterior; la guía de preparación ante apagones desarrolla el plan doméstico."},
      {heading:"Sí existe un informe técnico final",body:"ENTSO-E publicó el informe final del panel de expertos el 20 de marzo de 2026, tras el informe factual del 3 de octubre de 2025. Analiza las causas y formula recomendaciones, incluyendo aspectos de control de tensión, desconexiones de generación, oscilaciones y restauración. Por tanto, no es correcto afirmar que la existencia de debates posteriores implica que no se publicaron conclusiones técnicas.",links:[{label:"ENTSO-E: informes, cronología y recomendaciones",href:"https://www.entsoe.eu/publications/blackout/28-april-2025-iberian-blackout/"}]},
      {heading:"Qué no se puede concluir de una jornada institucional",body:"Que una institución siga debatiendo el suceso no prueba, por sí solo, que no se haya hecho nada ni que todas las recomendaciones estén implantadas. Para valorar una medida concreta, comprueba su texto, fecha, alcance y estado de ejecución. Una recomendación publicada y una actuación terminada son cosas diferentes."},
      {heading:"Lo aprendido en casa debe convertirse en una revisión",body:"En lugar de trasladar porcentajes de encuestas sin su ficha metodológica, repasa tu experiencia: qué dejó de funcionar, qué recurso faltó y qué persona necesitó ayuda. Tener una mochila no significa haber resuelto iluminación, comunicación, alimentos o necesidades específicas. Anota también lo que sí funcionó, para no comprar de nuevo algo que ya servía.",bullets:["Revisa iluminación, batería y medios de información.","Prevé alimentos que puedan consumirse sin cocinar; no improvises combustión en interiores.","Acuerda un plan si cada persona está en un lugar distinto.","Comprueba el material antes de otro corte, aunque sea local."]},
      {heading:"Preguntas frecuentes",body:"¿Se conoce una causa única? El informe analiza factores que interactúan; un eslogan no sustituye su lectura. ¿Puede garantizarse que no vuelva a pasar? Una investigación y sus recomendaciones no equivalen a una promesa de riesgo cero. ¿Hay que comprar un generador? No necesariamente: empieza por tus necesidades y por alternativas que puedas usar de forma segura."},
    ],relatedLinks:[{label:"Si aún no lo tienes resuelto, empieza por aquí: preparar un apagón",href:"/supervivencia/como-prepararse-para-un-apagon"},{label:"Listas de preparación",href:"/checklists"}],
  },
  "dana-aviso-naranja-o-rojo-que-debes-hacer":{
    excerpt:"Cómo interpretar el color, la zona y las horas de un aviso de AEMET, y por qué las instrucciones de Protección Civil no se sustituyen por una tabla de colores.",
    sections:[
      {heading:"El color es solo una parte del aviso",body:"Ante lluvias intensas, no te quedes con una captura compartida. Comprueba la fuente, cuándo se emitió, a qué zona afecta, qué fenómeno describe y entre qué horas es válido. El aviso meteorológico y las instrucciones de las autoridades son información complementaria: no significan exactamente lo mismo."},
      {heading:"Amarillo, naranja y rojo",body:"AEMET expresa los niveles en términos de peligro. El amarillo indica peligro bajo, con posibles impactos en personas, bienes o actividades vulnerables y expuestas. El naranja indica peligro importante y posibilidad de impactos graves. El rojo indica peligro extraordinario y posibles impactos muy graves o catastróficos. El riesgo concreto depende también de dónde estás y de tu vulnerabilidad.",links:[{label:"AEMET: interpretación oficial de los avisos",href:"https://www.aemet.es/es/eltiempo/prediccion/avisos/ayuda"}]},
      {heading:"Cómo adaptar la decisión",body:"Con amarillo, mantente informado y revisa tu exposición; no significa que cualquier actividad sea segura. Con naranja, toma precauciones y prepárate para cambiar planes. Con rojo, actúa conforme a las autoridades y evita viajar salvo necesidad estricta. Comprueba siempre las restricciones y recomendaciones concretas para tu localidad, en vez de convertir un color en una regla automática.",bullets:["Consulta la zona de aviso y el intervalo horario, no solo el municipio que aparece en una noticia.","Revisa las actualizaciones antes de salir y no esperes a observar daños para informarte.","Sigue los mensajes de Protección Civil y los servicios locales."]},
      {heading:"Aviso meteorológico no equivale a orden de evacuación",body:"No deduzcas de un aviso por sí solo que debes abandonar una vivienda, bajar al coche o iniciar un desplazamiento. Las decisiones dependen del episodio y de las instrucciones recibidas. Una lista doméstica ayuda a prepararse, pero no sustituye una orden oficial ni la valoración de una situación concreta."},
      {heading:"Preguntas frecuentes",body:"¿Puede cambiar el color durante el episodio? Sí: consulta la información actualizada. ¿Amarillo permite mantener cualquier plan? No; una actividad expuesta puede requerir cambios. ¿Dónde miro el aviso vigente? En AEMET y, para las medidas de protección, en los canales oficiales de tu comunidad y municipio.",links:[{label:"Consultar avisos vigentes de AEMET",href:"https://www.aemet.es/es/eltiempo/prediccion/avisos"}]},
    ],relatedLinks:[{label:"Preparar el plan familiar antes de un aviso",href:"/checklists"},{label:"Guía de preparación ante DANA",href:"/supervivencia/que-hacer-durante-dana"}],
  },
  "generador-en-casa-normativa-y-peligros-que-debes-evitar":{
    excerpt:"Monóxido de carbono, conexiones eléctricas y combustible: qué revisar con profesionales antes de plantearte un generador doméstico.",
    sections:[
      {heading:"Antes de comprar, comprueba si puedes usarlo",body:"Un generador de combustión no es una compra adecuada para cualquier vivienda. Antes de comparar potencia, necesitas un emplazamiento que cumpla las instrucciones de seguridad, un plan de almacenamiento y una solución eléctrica revisada por un instalador cuando corresponda. Si esas condiciones no se pueden cumplir, no improvises."},
      {heading:"El monóxido de carbono no avisa por su olor",body:"El CO es un gas sin color ni olor que puede causar una intoxicación mortal. Los CDC indican que los generadores deben funcionar en el exterior, a más de 20 pies, aproximadamente 6 metros, de puertas, ventanas y ventilaciones. No deben usarse en viviendas, garajes o sótanos, aunque se abran puertas. Un balcón o terraza no es automáticamente válido: los gases pueden entrar en la vivienda o en otras cercanas. Los detectores son una protección adicional, no un permiso para una ubicación inadecuada.",links:[{label:"CDC: monóxido de carbono y generadores",href:"https://www.cdc.gov/carbon-monoxide/about/index.html"}]},
      {heading:"Nunca lo conectes a un enchufe para alimentar la casa",body:"No improvises cables ni conexiones a la instalación. El Reglamento electrotécnico para baja tensión contempla requisitos específicos para instalaciones generadoras en la ITC-BT-40. La solución y su documentación dependen de la instalación; debe revisarlas una empresa instaladora habilitada. No basta con comprar una pieza y montarla sin evaluación profesional.",links:[{label:"BOE: Reglamento electrotécnico para baja tensión, ITC-BT-40",href:"https://www.boe.es/buscar/act.php?id=BOE-A-2002-18099"}]},
      {heading:"Una lista de preguntas antes de decidir",body:"Lleva tus necesidades concretas al profesional y consulta el manual del modelo. La potencia de arranque de algunos aparatos puede diferir de su consumo habitual. Evita convertir la suma de etiquetas en un diseño eléctrico.",bullets:["¿Qué cargas son realmente necesarias y cuáles no?","¿Existe un emplazamiento compatible con las distancias y el escape?","¿Cómo se revisarán ruido, combustible, mantenimiento y almacenamiento?","¿Qué instalación, permisos o documentación corresponden al caso?","¿Hay una alternativa sin combustión que cubra las tareas básicas?"]},
      {heading:"Preguntas frecuentes",body:"¿Un garaje abierto sirve? No elimina el riesgo de CO. ¿Un detector vuelve segura cualquier ubicación? No. ¿Hay una cantidad universal de combustible permitida en casa? No la damos: depende del producto y de los requisitos aplicables; consulta al organismo competente. ¿Una batería sustituye cualquier generador? Tampoco: comprueba cargas y límites sin confundir capacidad con potencia."},
    ],relatedLinks:[{label:"Si buscas una alternativa sin combustión, revisa estas limitaciones",href:"/supervivencia/powerbanks-solares-aguantan-un-apagon-largo"},{label:"Qué cambió tras el apagón",href:"/supervivencia/apagon-de-espana-de-2025-que-ha-cambiado-desde-entonces"}],
  },
  "verano-de-2026-el-mas-calido-de-la-serie-en-espana":{
    excerpt:"Qué mide el balance de AEMET del verano de 2026 y cómo distinguir una media estacional, un máximo local y los días acumulados de ola de calor.",
    sections:[
      {heading:"Qué récord describe AEMET",body:"En su balance del 21 de septiembre de 2026, AEMET sitúa la temperatura media de junio a agosto en la España peninsular en 24,5 °C: 2,4 °C sobre la referencia 1991-2020 y 0,3 °C por encima de 2025. Es el verano más cálido de la serie oficial iniciada en 1961. La media peninsular no equivale a la temperatura de cada ciudad ni a la máxima del verano.",links:[{label:"AEMET: balance del verano de 2026",href:"https://www.aemet.es/es/noticias/2026/09/resumen_verano2026"}]},
      {heading:"Los 61 días requieren contexto",body:"AEMET también comunicó 61 días acumulados bajo condiciones de ola de calor en Península y Baleares durante 2026. No significa una única ola continua ni que cada localidad registrase esas condiciones todos esos días. Tampoco debe dividirse sin más esa cifra entre los días de junio a agosto: el ámbito temporal del recuento importa.",links:[{label:"AEMET: información sobre días de ola de calor en 2026",href:"https://www.aemet.es/eu/noticias/2026/09/olas_de_calor_2026"}]},
      {heading:"Leer los datos sin mezclar escalas",body:"Antes de compartir un titular, comprueba tres etiquetas: territorio, periodo y variable. Una media nacional o peninsular, la máxima de una estación y un aviso sanitario responden a preguntas diferentes. Si un gráfico compara años, mira además si usa la misma referencia y metodología. Evita convertir una estimación estadística en un diagnóstico individual."},
      {heading:"Qué revisar en tu preparación",body:"El balance sirve para revisar el plan, no para conocer el aviso de hoy. Consulta las recomendaciones sanitarias vigentes para tu situación y los avisos actualizados de tu zona. Revisa con antelación quién necesita apoyo, cómo contactar y qué alternativas tienes para adaptar actividades. Las necesidades médicas individuales requieren orientación profesional.",bullets:["Separa la información histórica del aviso vigente.","Revisa el plan familiar antes del siguiente episodio.","Consulta al veterinario las necesidades de tus animales.","No uses una calculadora de sensación térmica como diagnóstico."]},
      {heading:"Preguntas frecuentes",body:"¿Los 24,5 °C fueron la máxima nacional? No: son una media estacional peninsular. ¿61 días significa una sola ola? No. ¿Un balance histórico dice qué tiempo hará mañana? No; consulta la predicción y los avisos actuales. ¿Se mantienen aquí las cifras de mortalidad del borrador? No: se han omitido porque requieren una referencia específica, periodo y metodología comprobables."},
    ],relatedLinks:[{label:"Preparación de mascotas ante calor y otras emergencias",href:"/supervivencia/mascotas-en-emergencias-apagon-calor-y-evacuacion"},{label:"Revisión de temporada",href:"/preparacion-practica/revision-por-temporadas"}],
  },
  "kit-de-emergencia-para-el-coche-que-llevar-en-2026":{
    excerpt:"Separa la señalización exigible del material de preparación y compara un kit premontado con uno adaptado a tus ocupantes y trayectos.",
    sections:[
      {heading:"Empieza por tu vehículo y tus trayectos",body:"Un kit no convierte una carretera peligrosa en transitable. Sirve para organizar material antes de salir, junto con la revisión del vehículo, la información del trayecto y las necesidades de sus ocupantes. Comprueba lo que ya tienes y evita llenar el maletero de duplicados sin saber dónde está cada cosa."},
      {heading:"La señalización cambió en 2026",body:"Desde el 1 de enero de 2026, la DGT indica la V16 conectada como dispositivo de preseñalización autorizado para los vehículos obligados a llevarlo en España. No copies una lista antigua que presenta los triángulos como requisito general vigente. Consulta la categoría de tu vehículo y las particularidades de circulación internacional. Verifica el modelo en el listado oficial: una luz parecida o una V16 no conectada no es equivalente.",links:[{label:"DGT: V16 conectada y listado de modelos certificados",href:"https://www.dgt.es/muevete-con-seguridad/tecnologia-e-innovacion-en-carretera/Dispositivos-de-presenalizacion-V16/"}]},
      {heading:"Material de preparación, aparte de lo reglamentario",body:"Adapta cantidades a ocupantes, trayecto y condiciones de conservación. No uses este listado como sustituto de las obligaciones de tráfico ni como protocolo para abandonar el vehículo.",bullets:["Agua y alimentos apropiados para cada persona, revisando envases y conservación.","Abrigo adecuado a la estación y necesidades del grupo.","Linterna comprobada y alimentación de repuesto compatible.","Cable y cargador o batería compatibles con el teléfono.","Botiquín revisado, documentación y contacto de asistencia.","Elementos reglamentarios comprobados para el vehículo concreto."]},
      {heading:"Premontado o preparado por ti",body:"Un kit premontado puede agrupar material en una compra, pero revisa cada componente: contenido, medidas, compatibilidad y calidad no se deducen del nombre del paquete. Montarlo tú permite aprovechar lo que ya tienes y adaptarlo; a cambio, necesitas una lista para no olvidar lo importante. Ninguna de las dos opciones garantiza que estés preparado para cualquier escenario."},
      {heading:"Dónde guardarlo y cuándo revisarlo",body:"Guarda cada elemento sin interferir con la conducción, con los sistemas del vehículo ni con los accesos. Consulta el manual para la ubicación de dispositivos y el mantenimiento. Revisa fechas y condiciones indicadas por los fabricantes, especialmente después de cambios de estación o de usar parte del material. No guardes combustible o fuentes de calor improvisadas como añadido al kit."},
      {heading:"Preguntas frecuentes",body:"¿Todo el contenido es obligatorio? No: distingue obligaciones reglamentarias y preparación voluntaria. ¿Los triángulos bastan en 2026? No para los vehículos españoles obligados a usar V16 conectada; revisa las excepciones aplicables. ¿Cuánto dura el agua en el coche? Sigue las condiciones de conservación y fecha del envase, sin prometer un plazo universal. ¿Un kit permite circular con cualquier aviso? No: respeta restricciones y recomendaciones oficiales."},
    ],relatedLinks:[{label:"Preparar también la mochila de casa",href:"/supervivencia/mejores-mochilas-de-emergencia-72h-en-espana-2026"},{label:"Interpretar los avisos meteorológicos",href:"/supervivencia/dana-aviso-naranja-o-rojo-que-debes-hacer"},{label:"Lista de revisión del vehículo",href:"/checklists"}],
  },
};
