import type { BlogPost } from './blog';
const common={category:'Actualidad y preparación',date:'27 septiembre 2026',publishedAt:'2026-09-27',readingTime:'5 min'};
const cover=(name:string,alt:string)=>({image:`/images/blog/${name}.jpg`,imageAlt:`${alt}. Escena ilustrativa generada con IA, no una emergencia real.`});
const links=[{label:'Listas de preparación familiar',href:'/checklists'},{label:'Calculadoras web',href:'/herramientas-supervivencia'}];
export const continuityArticles:BlogPost[]=[
 {
 ...common,...cover('reserva-agua-natural','Reserva de agua preparada en casa'),slug:'como-guardar-agua-emergencias',title:'Cómo guardar agua para emergencias',seoTitle:'Corte de agua prolongado: cómo preparar una reserva para 7 días',excerpt:'¿Qué harías si abrieras el grifo y no saliera agua durante varios días? Aprende a calcular tu reserva, almacenarla y organizar los usos.',keywords:['corte de agua prolongado','almacenar agua emergencia','agua supervivencia','cuánta agua almacenar','emergencia sin agua'],warning:'Siete días es un escenario de planificación, no un aviso de corte en España. El volumen almacenado no garantiza potabilidad. Sigue las instrucciones del suministrador y las autoridades sanitarias.',
 sections:[
 {heading:'Día uno, 07:12: abres el grifo y no sale nada',body:'Te levantas, entras en el baño y abres el grifo. Nada. Pruebas en la cocina: tampoco. Piensas que será una avería del edificio, pero llegan mensajes sobre una incidencia de suministro. Al principio esperas que vuelva pronto. Pasan las horas y empiezas a descubrir cuántas tareas dependían de abrir un grifo. Esta escena es hipotética: sirve para revisar tu vivienda antes de una interrupción real, no para anunciar una falta de agua en todo el país.'},
 {heading:'El agua potable es mucho más que beber',body:'Beber, preparar alimentos, lavarse las manos, limpiar y atender a mascotas o necesidades particulares son usos distintos. Una reserva destinada a beber no representa todo el consumo doméstico. Identifica qué actividades necesitan agua potable y cuáles admiten otras alternativas autorizadas, sin confundir los recipientes ni improvisar usos de agua contaminada.'},
 {heading:'Día dos: ¿cuánta agua necesita tu familia?',body:'Las botellas disminuyen y empiezan los cálculos. No hay una cantidad única que cubra cualquier persona y cualquier uso. Como referencia de almacenamiento de emergencia, los CDC recomiendan al menos un galón estadounidense, aproximadamente 3,8 litros, por persona y día durante tres días, para beber y otros usos básicos. No equivale a una pauta individual de bebida ni a todo el consumo habitual de una casa. Calor, embarazo, enfermedad y otras circunstancias pueden requerir más; consulta las necesidades sanitarias particulares.'},
 {heading:'Haz un cálculo explícito, no una suposición',body:'Multiplica personas por días y por el consumo que decidas planificar para cada uso. Por ejemplo, cuatro personas durante siete días a 3,8 litros diarios suman 106,4 litros. Es un ejemplo de presupuesto de agua, no una garantía de suficiencia para ese hogar. Añade por separado mascotas y necesidades no cubiertas. Solo el agua pesaría aproximadamente 106 kilos: reparte recipientes manejables y no concentres cargas importantes en una estantería inadecuada.',links:[{label:'Calcular autonomía de la reserva',href:'/blog/calculadora-gestion-agua-supervivencia#calculadora'}]},
 {heading:'Día tres: cada litro tiene una finalidad',body:'Separa claramente el agua potable de cualquier agua reservada para usos no alimentarios. Etiqueta estos últimos recipientes y evita que niños u otras personas puedan confundirlos. Que un uso no sea beber no significa que cualquier agua sirva: la higiene, el contacto con alimentos y determinados cuidados requieren condiciones específicas. Un aviso de no beber y uno de no utilizar el agua no son equivalentes; lee las instrucciones completas.'},
 {heading:'Cómo almacenar sin contaminar la reserva',body:'El agua embotellada comercialmente y sin abrir es una opción de reserva. Respeta las condiciones y fechas del fabricante. Para otros recipientes, utiliza envases aptos para agua y uso alimentario, limpios y con cierre; nunca reutilices uno que contuvo productos tóxicos. Guarda la reserva protegida del calor, del sol y de productos químicos. Identifica las fechas y establece revisiones: no basta con llenar un bidón y olvidarlo.'},
 {heading:'El error peligroso: beber cualquier agua',body:'Que el agua sea transparente no demuestra que sea segura. Puede contener microorganismos o sustancias que no ves. Hervir puede tratar riesgos microbiológicos, pero no elimina todos los contaminantes químicos; un filtro tampoco resuelve cualquier contaminación. Ante un aviso sanitario, sigue el método y las restricciones indicados para ese caso. Si no hay un tratamiento doméstico adecuado, necesitas otra fuente segura, no un experimento.'},
 {heading:'Día cinco: las botellas no son todo el plan',body:'Necesitas saber dónde publica avisos el suministrador, cómo se comunica el reparto de agua si lo hay, cómo transportar recipientes sin lesionarte y qué hacer si no puedes desplazarte. Planifica las necesidades de personas dependientes y animales. No salgas a buscar fuentes desconocidas ni utilices agua de inundación. Si las condiciones de la vivienda dejan de ser adecuadas, sigue las indicaciones de ayuda o traslado; una reserva no obliga a permanecer allí.'},
 {heading:'El reto de las 24 horas',body:'Observa durante un día cada uso del grifo: bebida, cocina, limpieza, ducha, lavadora y WC. No cortes el suministro ni limites necesidades esenciales para practicar. Anota qué podrías aplazar, qué requiere agua potable y qué alternativa realmente tienes. El objetivo no es llenar la vivienda de bidones: es conocer las necesidades, revisar tu reserva y tener una alternativa realista antes de la incidencia.'},
 ],sources:[{title:'CDC: crear y almacenar una reserva de agua de emergencia',url:'https://www.cdc.gov/water-emergency/about/how-to-create-and-store-an-emergency-water-supply.html'}],relatedLinks:[...links,{label:'Métodos y límites de potabilización',href:'/blog/potabilizar-agua-emergencia-metodos-seguros'}]
 },
 {
 ...common,...cover('aprendizaje-campo-natural','Preparación de información para una salida'),slug:'7-dias-sin-internet',title:'7 días sin Internet: el experimento que muestra cuánto dependemos de estar conectados',seoTitle:'7 días sin Internet: cómo prepararse para una caída prolongada',excerpt:'Mapas, mensajes, banca, trabajo y documentos: revisa qué seguiría disponible si tu conexión a Internet fallara durante varios días.',keywords:['caída de Internet','Internet caído','vivir sin Internet','comunicaciones emergencia','mapas offline','supervivencia digital'],warning:'Es un ejercicio hipotético, no una predicción. Una caída de Internet no implica necesariamente perder llamadas, SMS, GPS o contactos locales. No te desplaces a un lugar desconocido sin medios de orientación y comunicación seguros.',
 sections:[
 {heading:'Haz una prueba sin buscar en Internet',body:'¿Sabes el teléfono de tu pareja, el colegio o tu seguro? ¿Puedes encontrar una reserva de viaje fuera del correo? ¿Tienes apuntadas las direcciones importantes? No recordar esos datos no es un fallo personal: muchas tareas se han trasladado al teléfono y a servicios online. La pregunta útil es si podrías recuperarlos cuando ese servicio concreto no esté disponible.'},
 {heading:'Día uno: algo más que redes sociales',body:'En este escenario tu conexión deja de funcionar. No puedes enviar determinados mensajes, consultar páginas o usar algunas aplicaciones. Pero distingue las dependencias: los contactos guardados localmente pueden seguir accesibles, y una red telefónica operativa puede permitir llamadas o SMS aunque no tengas datos. Comprueba el alcance real de la incidencia antes de concluir que toda comunicación ha desaparecido.'},
 {heading:'Día dos: Internet también es infraestructura',body:'Necesitas hacer una transferencia, consultar un archivo, enviar un correo, comprobar un horario o revisar el tiempo. Descubres qué tareas dependen de una conexión y cuáles solo requieren información que podías haber preparado antes. Haz una lista de gestiones aplazables y de necesidades esenciales. No repitas operaciones bancarias sin comprobar su estado ni entregues tus claves a una supuesta asistencia que te contacte inesperadamente.'},
 {heading:'Día tres: desplazarte sin información en directo',body:'Un mapa descargado puede permitir consultar calles o determinadas rutas sin datos, según la aplicación. No ofrece necesariamente tráfico actualizado, cierres, horarios o todas las funciones del servicio online. El posicionamiento por satélite y la descarga del mapa son cosas diferentes: poder obtener una posición no significa tener cartografía disponible. Prepara la zona y una alternativa en papel antes de salir; no pruebes tus límites perdiéndote a propósito.'},
 {heading:'Día cuatro: el contacto estaba detrás de un nombre',body:'Siempre pulsabas un nombre y no recordabas el número. Primero comprueba si el contacto está guardado en el dispositivo: no todo requiere Internet. La alternativa en papel protege también frente a una batería agotada, pérdida o avería del móvil. Acuerda con la familia qué hacer si no podéis comunicaros, evitando desplazamientos improvisados para buscar señal.'},
 {heading:'Tu kit digital offline',body:'Elige información útil, no una copia indiscriminada de tu vida. Comprueba que los archivos abren sin descargar contenido adicional ni iniciar sesión de nuevo. Protege los datos personales y revisa quién tiene acceso.',bullets:['Mapas de las zonas necesarias y direcciones importantes.','Contactos familiares y teléfonos oficiales de servicios habituales.','Documentación esencial, con protección adecuada y límites de validez conocidos.','Guías, manuales y datos necesarios para tus circunstancias particulares.','Puntos de encuentro y acuerdos familiares también fuera del teléfono.']},
 {heading:'Papel: una alternativa sin batería',body:'Una tarjeta con teléfonos y un punto de encuentro no necesita servidor, cobertura ni cargador. Pero puede perderse o ser leída por otros: evita incluir contraseñas, códigos de recuperación o más datos sensibles de los necesarios. Guarda las copias de forma proporcionada al riesgo. La preparación moderna combina herramientas digitales con alternativas sencillas; no exige elegir un solo sistema.'},
 {heading:'La prueba definitiva, desde un lugar seguro',body:'Haz una prueba breve en casa con un documento ficticio y un mapa descargado de una zona conocida. Activa modo avión solo cuando no comprometa comunicaciones necesarias: desactiva llamadas y datos habituales mientras esté activo. No lo uses como experimento durante una emergencia ni te lances a una dirección desconocida sin alternativa. Restablece la conexión al terminar y anota qué faltó. La app Modo Crisis Survival puede complementar esa preparación, siempre que hayas descargado y comprobado los recursos antes.'},
 ],sources:[{title:'INCIBE: consejos para evitar riesgos en línea',url:'https://www.incibe.es/sites/default/files/2024-12/tips-para-evitar-riesgos-en-linea.pdf'}],relatedLinks:[...links,{label:'Mapas y posición sin Internet',href:'/blog/gps-movil-sin-internet-mapas-offline'},{label:'Preparación ante un ciberataque',href:'/blog/ciberataque-masivo-servicios-esenciales'}]
 },
 {
 ...common,...cover('familia-preparada-natural','Organización de recursos en el hogar'),slug:'tarjetas-cajeros-pagos-no-funcionan',title:'Cuando el dinero deja de funcionar: qué hacer si fallan tarjetas, cajeros y pagos móviles',seoTitle:'¿Qué hacer si tarjetas y cajeros dejan de funcionar?',excerpt:'Un apagón o fallo de telecomunicaciones puede afectar temporalmente los pagos electrónicos. Cómo prepararte sin guardar grandes cantidades de efectivo.',keywords:['tarjetas no funcionan','cajeros no funcionan','efectivo emergencia','pagar durante apagón','caída sistema bancario'],
 sections:[
 {heading:'Tienes dinero, pero no puedes completar el pago',body:'Imagina que vas a pagar en una gasolinera. El móvil da error; después la tarjeta. El empleado explica que no tiene conexión y el cajero próximo tampoco funciona. Es un escenario de indisponibilidad temporal: no demuestra que tu saldo haya desaparecido o que un banco haya quebrado. Antes de repostar o contratar un servicio durante una incidencia conocida, pregunta qué formas de pago están disponibles.'},
 {heading:'Ya hemos visto interrupciones reales',body:'El Banco de España ha analizado la experiencia del apagón de abril de 2025. Un terminal, un cajero y los sistemas centrales de una entidad tienen dependencias y respaldos diferentes. Puede funcionar la plataforma y fallar el acceso del comercio. No generalices desde un mensaje de error: consulta al establecimiento o a tu entidad por canales conocidos y comprueba si una operación llegó a ejecutarse antes de repetirla.'},
 {heading:'Tres dispositivos no son tres alternativas independientes',body:'Móvil, reloj y tarjeta resultan cómodos, pero pueden terminar dependiendo del mismo terminal o conexión. Disponer de otra tarjeta puede resolver ciertos problemas particulares, pero no un fallo común del comercio. La preparación consiste en conocer qué alternativa sirve en cada caso, no en sumar dispositivos como si todos fueran independientes.'},
 {heading:'¿Guardar miles de euros en casa? No es la propuesta',body:'Una reserva excesiva introduce riesgos de robo, pérdida o incendio. Valora una cantidad limitada y proporcionada a los gastos esenciales de tu hogar y a tus posibilidades. Billetes de importes pequeños y algunas monedas pueden facilitar pagos cuando hay poco cambio. Ninguna cifra garantiza resolver todas las necesidades ni que un comercio pueda abrir durante una emergencia.'},
 {heading:'Prepara un segundo medio de pago',body:'Revisa las tareas concretas que no podrías aplazar y las alternativas disponibles en tu entorno. Mantén protegida la información bancaria y no conviertas una hoja de contactos en una lista de contraseñas.',bullets:['Una reserva prudente de efectivo, guardada de forma segura.','Más de un medio de pago cuando sea adecuado para ti, conociendo sus dependencias.','Teléfonos oficiales de la entidad y acceso por su web o aplicación habitual.','Comprobación de cargos pendientes y justificantes para evitar pagos duplicados.','Un plan doméstico que reduzca compras urgentes por necesidades previsibles.']},
 {heading:'Cuidado con el fraude durante la incidencia',body:'Un mensaje sobre una cuenta bloqueada puede aprovechar una avería real para pedir credenciales. No abras enlaces inesperados para recuperar acceso, no reveles códigos de un solo uso y no transfieras dinero a una supuesta cuenta segura indicada por quien te llama. Accede por tu canal habitual o contacta con la entidad mediante un número verificado previamente.'},
 {heading:'El experimento de los veinte euros',body:'El título del ejercicio no es una recomendación de cantidad. Imagina que solo dispones de veinte euros en efectivo y que tus tarjetas no funcionan durante un día: ¿qué gasto esencial podrías afrontar y cuál quedaría sin resolver? Hazlo sobre papel, sin retirar grandes sumas ni cambiar tus hábitos financieros por miedo. El resultado sirve para identificar alternativas, no para prometer que una cifra concreta basta a cualquier familia.'},
 {heading:'Una incidencia no exige una decisión precipitada',body:'Consulta información confirmada, evita repetir intentos sin revisar su resultado y conserva los justificantes necesarios. No difundas como quiebra una caída de una aplicación. La idea es disponer de margen durante una interrupción, no abandonar los pagos digitales ni vivir pendiente de una crisis bancaria.'},
 ],sources:[{title:'Banco de España: cómo pagamos cuando se va la luz',url:'https://www.bde.es/wbe/es/noticias-eventos/blog/como-pagamos-cuando-todo-se-apaga-la-experiencia-del-apagon-en-espana.html'}],relatedLinks:[...links,{label:'Prepararse para un apagón',href:'/blog/como-prepararse-para-un-apagon'},{label:'Detectar mensajes falsos en una emergencia',href:'/blog/desinformacion-emergencias-deepfakes-alertas-falsas'}]
 },
 {
 ...common,...cover('lluvia-prevencion-editorial','Entorno urbano con lluvia'),slug:'que-hacer-durante-dana',title:'Qué hacer durante una DANA o inundación',seoTitle:'DANA: cómo prepararte si quedas aislado durante 72 horas',excerpt:'Una inundación puede cortar carreteras, electricidad y comunicaciones. Prepara tu vivienda y conoce las prioridades si quedas temporalmente aislado.',keywords:['qué hacer durante una DANA','DANA emergencia','inundación qué hacer','preparar casa DANA','kit emergencia inundación'],warning:'Las 72 horas son un escenario de preparación, no un plazo de espera ni una garantía de seguridad. Ante peligro inmediato solicita ayuda al 112 y sigue las instrucciones oficiales. No permanezcas en un lugar peligroso por conservar tu reserva.',
 sections:[
 {heading:'Empieza a llover y cambia la pregunta',body:'En esta escena hipotética llueve durante horas. Llega una alerta y la carretera habitual comienza a acumular agua. Un mensaje oficial pide evitar desplazamientos. La pregunta deja de ser cuándo parará de llover y pasa a ser si el lugar donde estás es seguro y cómo atender sus necesidades. Una DANA no provoca por sí sola el mismo impacto en todas partes: consulta el episodio, la zona y las instrucciones concretas.'},
 {heading:'No conviertas el coche en una trampa',body:'No atravieses tramos inundados a pie ni en vehículo. Desde dentro del coche es difícil valorar la profundidad, la corriente, el estado del firme y los obstáculos. No salgas a comprobar la carretera ni a fotografiar la situación. Si quedas aislado y necesitas ayuda, informa de tu ubicación y circunstancias a emergencias; no improvises un cruce para salir.'},
 {heading:'El garaje no merece arriesgar tu vida',body:'El impulso de bajar a salvar el vehículo puede llevarte a una zona que se inunda rápidamente. No entres en sótanos ni garajes amenazados por el agua para recuperar pertenencias. Prepara antes la documentación y los objetos esenciales fuera de zonas expuestas, cuando sea seguro hacerlo. Ya durante la inundación, la prioridad son las personas, no los bienes.'},
 {heading:'Las primeras horas, solo si el lugar es seguro',body:'Prepara dispositivos e iluminación mientras puedas hacerlo sin exponerte a agua o instalaciones dañadas. No toques aparatos enchufados y mojados. Mantén a mano agua segura, comida, medicación, radio, batería, documentación, ropa y lo necesario para menores o mascotas. Una lista ayuda a organizarte, pero no debe retrasar una salida indicada por las autoridades.'},
 {heading:'¿Evacuar o quedarse?',body:'Ningún artículo puede decidirlo por ti durante una emergencia activa. Sigue las instrucciones de Protección Civil y emergencias para tu ubicación. Si ordenan evacuar, utiliza el procedimiento indicado; si piden permanecer en un lugar seguro, no hagas desplazamientos innecesarios. Si tu situación concreta presenta peligro inmediato, comunícala y solicita ayuda. No esperes 72 horas ni trates una reserva doméstica como permiso para permanecer expuesto.'},
 {heading:'Prepara alternativas antes del aviso',body:'Conoce la salida habitual, otra alternativa, zonas inundables y puntos de encuentro. No asumas que una ruta descargada o utilizada a diario seguirá abierta. Las instrucciones y condiciones reales prevalecen sobre el mapa. Acuerda cómo ayudar a personas con movilidad limitada y qué hacer si la familia está separada.'},
 {heading:'La mochila debe estar preparada antes',body:'Localiza documentación esencial, tratamientos prescritos, iluminación, batería, ropa y recursos adaptados al hogar. Prevé agua y alimentos que puedas transportar sin una carga desproporcionada. Incluye necesidades infantiles y de mascotas. No esperes a que entre agua para buscarlo todo, y no vuelvas a una zona peligrosa a por la mochila.'},
 {heading:'Después, no vuelvas hasta que sea seguro',body:'El descenso del agua no elimina todos los riesgos. Puede haber daños estructurales, instalaciones eléctricas afectadas, huecos y contaminación. Sigue las indicaciones oficiales de acceso y de agua potable; no manipules equipos dañados para intentar recuperar la normalidad de inmediato. Solicita la evaluación adecuada cuando corresponda.'},
 {heading:'La pregunta incómoda',body:'Si recibieras una orden de evacuación, ¿sabes dónde están los elementos imprescindibles y quién necesita ayuda? Ensaya localizar la documentación y explicar el punto de encuentro, en un día tranquilo. No salgas a comprobar rutas durante un episodio ni conviertas el ejercicio en una carrera: sirve para detectar lo que falta antes de necesitarlo.'},
 ],sources:[{title:'Protección Civil: autoprotección ante inundaciones',url:'https://www.proteccioncivil.es/documents/20121/0/08-Inundaciones_accesible.pdf/9b11b38f-447a-5eea-38bd-088def20096f'},{title:'AEMET: avisos meteorológicos vigentes',url:'https://www.aemet.es/es/eltiempo/prediccion/avisos'}],relatedLinks:[...links,{label:'Diferenciar avisos y alertas',href:'/blog/diferencias-alertas-oficiales-avisos-meteorologicos'},{label:'Preparación frente a riesgos climáticos',href:'/blog/espana-2030-calor-sequia-inundaciones'}]
 },
 {
 ...common,...cover('mochila-familiar-editorial','Preparación familiar de recursos esenciales'),slug:'primeras-24-horas-gran-emergencia',title:'Las primeras 24 horas después de una gran emergencia: las decisiones que pueden cambiarlo todo',seoTitle:'Primeras 24 horas de una emergencia: prioridades para actuar',excerpt:'Las primeras horas de una emergencia pueden ser confusas. Aprende a ordenar prioridades sin sustituir las instrucciones específicas de cada riesgo.',keywords:['qué hacer en una emergencia','primeras 24 horas emergencia','supervivencia urbana','plan emergencia familiar','kit 72 horas'],warning:'Esta secuencia organiza un ejercicio doméstico, no es un protocolo universal ni fija tiempos de espera. Incendios, terremotos e inundaciones exigen respuestas diferentes. El peligro inmediato y las instrucciones oficiales tienen prioridad.',
 sections:[
 {heading:'00:00: algo acaba de ocurrir',body:'Un corte de luz, una inundación, un incendio cercano o una interrupción de comunicaciones generan preguntas. Quieres saber qué está pasando, pero comprender toda la causa no debe retrasar proteger a una persona. El tipo de riesgo sí importa: no hay una maniobra única válida para cualquier emergencia. No confundas esta cronología ilustrativa con instrucciones para esperar a una hora determinada.'},
 {heading:'Primeros minutos: peligro, personas y lugar',body:'Identifica señales de peligro desde una posición segura: humo, fuego, agua, daños, cables o cristales. No te acerques a inspeccionarlos ni intentes eliminarlos sin capacidad y seguridad. Comprueba a las personas próximas y las necesidades de quien depende de ayuda. Ante una emergencia real, solicita asistencia al 112 y sigue las instrucciones adecuadas al riesgo; no esperes a completar una lista.'},
 {heading:'Información que cambia decisiones',body:'Cuando sea seguro, consulta qué zona está afectada y qué medidas recomiendan las autoridades. No retrases una orden urgente para contrastarla con un segundo mensaje ni difundas rumores. Buscar la explicación completa del suceso es menos importante que conocer la instrucción aplicable a tu ubicación. No llames a emergencias solo para preguntar por una avería general.'},
 {heading:'Un inventario rápido, si puedes permanecer con seguridad',body:'Revisa agua, comida, medicación, iluminación, baterías, información y documentación. Localiza familiares y mascotas sin entrar en zonas peligrosas. No almacenes combustible ni improvises fuentes de calor por esta lista. Al principio basta con saber qué recursos están realmente disponibles y quién necesita atención, no con diseñar una reserva perfecta.'},
 {heading:'Horas dos a seis: administrar lo disponible',body:'Si la interrupción continúa y no hay una prioridad más urgente, reduce usos innecesarios del móvil, organiza la iluminación y evita abrir repetidamente frigorífico y congelador. Revisa la calidad y destino del agua, no solo su volumen. Acuerda comunicaciones familiares breves cuando sean posibles y conserva una alternativa si el teléfono se queda sin batería.'},
 {heading:'Horas seis a doce: convivir con la incertidumbre',body:'Puede que nadie conozca todavía cuánto durará la situación. No tomes decisiones importantes basándote en un audio que promete una hora exacta de restablecimiento. Trabaja con la información confirmada y prepara alternativas. Reparte tareas asequibles, comprueba cómo están las personas y revisa si han cambiado las instrucciones o el riesgo del lugar.'},
 {heading:'Pensar más allá de la próxima hora',body:'Si la emergencia continúa, revisa cuánta agua segura queda, qué comidas son viables, quién necesita medicación o ayuda y qué temperatura o condiciones se esperan. Comprueba si sigue siendo seguro permanecer donde estás. El paso del tiempo no convierte una vivienda insegura en un refugio adecuado ni justifica retrasar una solicitud de asistencia.'},
 {heading:'P.A.R.A.: una ayuda para recordar, no un protocolo oficial',body:'Puedes usar estas letras como recordatorio editorial. No sustituyen formación, primeros auxilios ni instrucciones de Protección Civil, y su orden no impide priorizar una necesidad urgente.',bullets:['P: Peligro. Evita la exposición y solicita ayuda; no intentes resolver un riesgo que no puedes controlar.','A: Agua y necesidades esenciales. Revisa recursos y necesidades particulares cuando estés seguro.','R: Reunión e información. Localiza a la familia sin desplazamientos peligrosos y consulta fuentes fiables.','A: Administración. Organiza recursos y alternativas según la situación real.']},
 {heading:'Tener material no equivale a estar preparado',body:'Una linterna que nadie encuentra, una batería descargada o un plan desconocido por la familia no resuelven mucho. Comprueba el funcionamiento de lo que ya tienes y sus límites. Un filtro o un mapa no garantizan agua segura ni una ruta transitable. La preparación consiste también en saber cuándo no usar un recurso o cuándo pedir ayuda.'},
 {heading:'Ensaya dos horas sin crear un riesgo',body:'Haz un ejercicio de mesa un fin de semana: imagina que faltan luz y datos, localiza las linternas y explica los acuerdos familiares. No desconectes la instalación, equipos médicos, alarmas, refrigeración ni comunicaciones esenciales. Utiliza documentos ficticios para probar copias offline. Anota las carencias y resuelve una cada vez. El objetivo no es vivir esperando algo malo, sino conocer mejor tus alternativas.'},
 {heading:'Prepárate antes y decide con más información',body:'Modo Crisis Survival complementa el plan con guías, checklists, mapas y recursos preparados para uso principalmente offline. Descarga y prueba lo que necesites antes, conoce qué funciones requieren conexión y conserva alternativas fuera del móvil. Ninguna app sustituye la seguridad del lugar, la ayuda profesional ni las instrucciones de una emergencia activa.'},
 ],sources:[{title:'Protección Civil: recomendaciones por tipo de riesgo',url:'https://www.proteccioncivil.es/gestion-riesgos/recomendaciones'}],relatedLinks:[...links,{label:'Simulacro familiar tranquilo',href:'/blog/simulacro-familiar-emergencia-30-minutos'},{label:'Comprobar información durante una emergencia',href:'/blog/desinformacion-emergencias-deepfakes-alertas-falsas'}]
 }
];
export const continuityUpdates = new Set(['como-guardar-agua-emergencias','que-hacer-durante-dana']);
