import type { BlogPost, BlogSection } from './blog';

export const everydayUpdates = new Set(['objetos-de-casa-que-pueden-ayudarte-en-una-emergencia', '5-mitos-de-supervivencia-que-pueden-ponerte-en-peligro']);
export const everydayAliases: Record<string, string> = {
  'objetos-cotidianos-utiles-emergencia': 'objetos-de-casa-que-pueden-ayudarte-en-una-emergencia',
  'mitos-supervivencia-cine': '5-mitos-de-supervivencia-que-pueden-ponerte-en-peligro',
};
const sections = (rows: string[][]): BlogSection[] => rows.map(([heading, body]) => ({ heading, body }));
const common = { category: 'Supervivencia práctica', date: '28 septiembre 2026', publishedAt: '2026-09-28', readingTime: '5 min' };
const app: BlogSection = { heading: 'Convierte la lectura en preparación', body: 'Elige una mejora pequeña y hazla hoy. Modo Crisis Survival permite preparar información, listas y recursos para consultar principalmente sin conexión. Descarga lo necesario y comprueba qué funciona sin Internet antes de depender de ello. Conserva contactos y acuerdos importantes también en papel.', links: [{ label: 'Conocer la app y descargar para Android', href: '/aplicacion-supervivencia-offline' }, { label: 'Revisar mi checklist', href: '/checklists' }] };
const mountain = { title: 'Guardia Civil: prevención y rescate en montaña', url: 'https://www.guardiacivil.es/documentos/Consejos/rescate_en_montana.pdf' };
export const everydayArticles: BlogPost[] = [
  {
    ...common, slug: 'objetos-de-casa-que-pueden-ayudarte-en-una-emergencia',
    title: '20 objetos normales que pueden ayudarte en una emergencia',
    seoTitle: '20 objetos cotidianos útiles en una emergencia',
    excerpt: 'Antes de comprar un kit, mira en casa: 20 objetos cotidianos, sus usos prácticos y los límites que conviene conocer para no improvisar peligros.',
    image: '/images/blog/familia-preparada-natural.jpg', imageAlt: 'Preparación de material doméstico para una emergencia. Imagen ilustrativa.',
    keywords: ['objetos útiles para supervivencia', 'kit emergencia casero', 'objetos supervivencia caseros'],
    sections: [...sections([
      ['Olvida cinco minutos las tiendas de supervivencia', 'No tienes equipo militar, pero sí una casa llena de recursos. Una bolsa protege ropa, una libreta conserva teléfonos y un frontal deja las manos libres. El objetivo no es inventar usos espectaculares: es localizar lo que ya funciona y conocer sus límites. Reúne estos objetos sin comprar nada y marca los que de verdad sabes utilizar.'],
      ['1. Bolsas de basura resistentes', 'Sirven para separar ropa mojada, recoger residuos y proteger material de la lluvia. No son recipientes alimentarios ni equipos de flotación. Nunca cubras la cabeza ni las utilices de una forma que pueda provocar asfixia; mantenlas fuera del alcance de menores.'],
      ['2. Film transparente', 'Agrupa pequeños objetos o cubre recipientes adecuados. Puede reducir salpicaduras, pero no vuelve estanco un teléfono ni esteriliza material. Evita envolver baterías calientes, enchufes o elementos que necesitan ventilación.'],
      ['3. Papel de aluminio', 'Envuelve alimentos según su uso previsto y ayuda a separar material. No lo metas en conexiones eléctricas ni improvises hornillos o reparaciones de fusibles. Tener una lámina metálica no equivale a disponer de un recipiente de cocina seguro.'],
      ['4. Un espejo pequeño', 'Con luz solar puede llamar la atención mediante reflejos. Practica su orientación en un lugar seguro antes de necesitarlo. No deslumbres conductores ni dependas únicamente de él: de noche o con cielo cubierto necesitas otra alternativa.'],
      ['5. Botellas adecuadas y limpias', 'Permiten transportar agua potable y medir cantidades. Utiliza recipientes aptos para alimentos; nunca reutilices envases de productos químicos. Etiqueta el contenido y recuerda que envasar agua desconocida no la hace potable.'],
      ['6. Toallas', 'Secan, acolchan objetos frágiles y aportan abrigo limitado. Guarda alguna seca y accesible. Una toalla húmeda no sustituye ropa térmica ni un botiquín; tampoco protege frente a gases o humo tóxico.'],
      ['7. Linterna frontal', 'Deja ambas manos libres para caminar por una zona segura o localizar material. Comprueba pilas, carga y ajuste. Busca autonomía y facilidad de uso antes que una cifra enorme de potencia. No esperes al apagón para descubrir cómo se enciende.'],
      ['8. Bridas', 'Agrupan cables y sujetan material en reparaciones temporales no estructurales. No sirven para escalada, rescate, sujeción de personas ni reparaciones de las que dependa tu seguridad. Evita tensarlas sobre cables deteriorados.'],
      ['9. Cinta adhesiva resistente', 'Cierra embalajes, marca objetos o ayuda en pequeños arreglos provisionales. Una unión pegada no garantiza resistencia, impermeabilidad ni aislamiento eléctrico. No tapes ventilaciones o salidas por iniciativa propia.'],
      ['10. Rotulador permanente', 'Identifica mochilas y recipientes, anota una hora o escribe un teléfono en una tarjeta. Marca únicamente superficies adecuadas, no piel ni medicamentos. Comprueba que escribe después de meses guardado.'],
      ['11. Libreta', 'Guarda teléfonos, direcciones, acuerdos y datos recibidos de fuentes oficiales. Anota fecha y procedencia para no confundir un aviso antiguo con uno vigente. Lleva solo los datos personales necesarios y protege la libreta.'],
      ['12. Silbato', 'Permite llamar la atención sin gritar continuamente. Déjalo accesible, no al fondo de una bolsa. Es una ayuda para señalizar, no una garantía de que alguien esté cerca o pueda oírte.'],
      ['13. Guantes de trabajo', 'Protegen en tareas compatibles con su resistencia. No autorizan a tocar cables, sustancias desconocidas o escombros inestables. Tras una emergencia, evitar una zona peligrosa sigue siendo mejor que entrar en ella con guantes.'],
      ['14. Bolsas con cierre', 'Organizan documentos y pequeños accesorios, con protección limitada frente a humedad. Conserva medicamentos en su envase y según sus condiciones de almacenamiento. Una bolsa corriente no garantiza inmersión ni conservación térmica.'],
      ['15. Una sábana', 'Puede servir de abrigo ligero, sombra o separación visual en un entorno seguro. No la conviertas en cuerda de descenso, arnés o sistema para mover una persona lesionada. Su resistencia no está certificada para rescate.'],
      ['16. Imperdibles', 'Resuelven pequeños desgarros de ropa. Guárdalos cerrados y lejos de menores. No los uses para procedimientos sanitarios ni para reparar material cuya rotura pueda causar una caída.'],
      ['17. Un mechero', 'Solo tiene utilidad donde encender fuego sea seguro y esté permitido. Ante olor a gas o vapores inflamables, no lo uses. Para iluminar una casa es preferible una linterna; tener un mechero no obliga a hacer fuego.'],
      ['18. Calzado cerrado', 'Déjalo accesible si necesitas salir de madrugada. Debe ajustar bien y permitir caminar; una suela fina no protege de cualquier objeto cortante. Mantén despejado el recorrido hacia la salida.'],
      ['19. Acceso a las llaves de corte', 'Conoce dónde están y consulta previamente cómo actuar en tu vivienda. No manipules gas o electricidad sin saber hacerlo ni entres en agua para alcanzar un cuadro. Sigue instrucciones profesionales ante una incidencia.'],
      ['20. Tu teléfono', 'Puede conservar mapas, notas y contactos sin Internet si los preparaste antes. La posición GPS y los mapas descargados son funciones distintas. Prueba los recursos offline y reserva batería para comunicación necesaria, no para experimentar durante la emergencia.'],
      ['Tu siguiente paso: una caja, tres prioridades', 'Localiza luz, contactos y protección para documentos. Comprueba su estado y acuerda dónde guardarlos. No hace falta reunir veinte objetos por obligación: cubre carencias reales y deja fuera los inventos que introducen riesgos. ¿Alguien más en casa sabe encontrarlos? Esa pregunta vale más que añadir otro accesorio.'],
    ]), app],
  },
  {
    ...common, slug: 'psicologia-emergencia-errores-mentales',
    title: 'Tu cerebro bajo presión: 7 trampas mentales durante una emergencia',
    seoTitle: 'Psicología de supervivencia: 7 errores en una emergencia',
    excerpt: 'Restar importancia a una alarma, seguir a la multitud o buscar certezas puede retrasarte. Prepara decisiones sencillas antes de necesitar tomarlas bajo presión.',
    image: '/images/blog/familia-preparada-natural.jpg', imageAlt: 'Preparación familiar de recursos y decisiones antes de una emergencia. Imagen ilustrativa.',
    keywords: ['psicología de supervivencia', 'reacción ante emergencia', 'decisiones supervivencia'],
    warning: 'Son pautas de preparación, no un diagnóstico psicológico ni una garantía sobre cómo reaccionará una persona. Ante peligro inmediato, prioriza protegerte y seguir las indicaciones de emergencias.',
    sections: [...sections([
      ['Mismo lugar, distinta decisión', 'Dos personas oyen la misma alarma. Una busca la salida señalizada y otra espera a que alguien confirme qué ocurre. No es una prueba de valentía ni inteligencia: bajo presión es difícil interpretar señales incompletas. Prepararse reduce decisiones pendientes. Estas siete situaciones sirven para revisar hábitos, no para culpar a quien se bloquea.'],
      ['1. «Seguro que no es para tanto»', 'La normalidad cotidiana invita a explicar una señal extraña como algo sin importancia. Si hay alarma, humo u otra señal objetiva, no retrases la protección para comprobar personalmente el origen. Sigue el protocolo del lugar. No necesitas demostrar que existe un incendio antes de atender una orden de evacuación.'],
      ['2. Seguir a los demás', 'Una fila de personas no demuestra que la primera conozca una ruta segura. Prioriza señalización e instrucciones del personal responsable. Antes de un incidente, identifica las salidas de tu trabajo o alojamiento. Tener una referencia propia evita que tu única opción sea copiar a quien tienes delante.'],
      ['3. Volver a por objetos', 'El teléfono, un ordenador o el coche pueden parecer imprescindibles. Pero volver puede exponerte otra vez al peligro. Prepara documentación y necesidades críticas antes; durante una salida urgente, las personas van primero. No reentres en una zona peligrosa para recuperar material o buscar una mascota: informa a los servicios de emergencia.'],
      ['4. Esperar información perfecta', 'Quizá todavía nadie sabe la causa o duración del incidente. Distingue lo que necesitas saber para la siguiente acción segura de lo que puede esperar. Una instrucción clara de evacuar no necesita una explicación completa del suceso para ser atendida. Evita convertir la búsqueda de noticias en una excusa para no actuar.'],
      ['5. Consumir mensajes hasta bloquearte', 'Veinte mensajes contradictorios no son veinte fuentes independientes. Elige canales oficiales y comprueba zona, hora e instrucción. Acuerda quién comunica al resto la información confirmada. No llames al 112 solo para contrastar rumores: reserva esa vía para emergencias.'],
      ['6. «A mí no me pasará»', 'Prepararse no exige creer que una catástrofe sea inminente. Basta con admitir que una avería, una evacuación o una pérdida de cobertura son posibles. Elige una medida proporcionada: guardar un contacto, cargar una batería o revisar una salida. Una acción pequeña resulta más útil que una lista perfecta que nunca empiezas.'],
      ['7. Decidir agotado', 'Después de muchas horas de incertidumbre cuesta mantener la atención. Una checklist corta y tareas repartidas reducen lo que debes recordar. Descansa cuando sea seguro y pide apoyo si lo necesitas. No conduzcas ni emprendas recorridos arriesgados por demostrar que puedes continuar.'],
      ['Un ejercicio sin sustos', 'En un momento tranquilo, plantead una incidencia hipotética y responded tres preguntas: qué peligro existe, qué instrucción tenemos y cuál es el siguiente paso seguro. No simules alarmas reales ni asustes a menores. Anotad contactos, responsabilidades y necesidades de apoyo. La práctica debe dejar acuerdos, no miedo.'],
      ['¿Y si me bloqueo?', 'Pide ayuda y comunica lo que necesitas con frases sencillas. No prometas mantener siempre la calma ni juzgues la reacción de otra persona. Los planes deben incluir apoyo a quienes lo necesiten. Si después de una experiencia difícil persiste un malestar que afecta a tu vida, consulta con profesionales.'],
    ]), app],
    relatedLinks: [{ label: 'Plan familiar de emergencia', href: '/supervivencia/como-crear-plan-familiar-emergencia' }],
  },
  {
    ...common, slug: 'que-hacer-si-te-pierdes-24-horas',
    title: '24 horas perdido: qué hacer para facilitar tu localización',
    seoTitle: 'Qué hacer si te pierdes: primeras decisiones y rescate',
    excerpt: 'El sendero desaparece y queda poca batería. Detente, evalúa el lugar, pide ayuda cuando la necesites y evita ampliar sin rumbo la zona de búsqueda.',
    image: '/images/blog/caza-observacion-editorial.jpg', imageAlt: 'Entorno natural para observar el terreno durante una salida. Imagen ilustrativa.',
    keywords: ['qué hacer si te pierdes', 'perdido montaña', 'supervivencia 24 horas'],
    warning: 'No esperes 24 horas para pedir ayuda si la necesitas. Este artículo no sustituye las instrucciones del 112 ni permite valorar a distancia la seguridad del terreno.',
    sources: [mountain],
    sections: [...sections([
      ['17:42: el camino ya no se parece al de antes', 'Llevas horas andando, el móvil marca 8 % y has probado otra senda que tampoco reconoces. El impulso es seguir hasta la siguiente curva. Antes de hacerlo, detente en un punto seguro. Este relato es hipotético: no hay una cuenta atrás universal, pero sumar kilómetros sin criterio puede complicar tu localización.'],
      ['STOP: una pausa para elegir el siguiente paso', 'Stop, Think, Observe, Plan: detente, piensa, observa y planifica. Es un recordatorio, no un protocolo que resuelva todos los terrenos. Comprueba peligros inmediatos, estado del grupo, luz disponible y último punto conocido. No te quedes inmóvil en una zona expuesta a una crecida, caída de piedras u otro peligro.'],
      ['Pide ayuda antes de agotar tus opciones', 'Si necesitas rescate, intenta contactar con el 112. Describe quién eres, cuántas personas hay, estado físico, ruta prevista, último lugar reconocido y material disponible. Facilita coordenadas si sabes obtenerlas y sigue las instrucciones. No te expongas en un cortado para buscar señal. Una llamada necesita alguna red disponible; no está garantizada en cualquier lugar.'],
      ['Con poca batería, conserva la comunicación', 'Reduce brillo y uso innecesario de pantalla. No apagues comunicaciones ni actives modo avión si esperas contacto de rescate, salvo indicación. Un mapa previamente descargado puede abrir sin Internet; no implica que puedas enviar tu posición. Anota o comunica referencias útiles en vez de consumir batería con búsquedas repetidas.'],
      ['Quedarte o moverte depende del peligro', 'Si estás seguro y te indican permanecer, desplazarte sin avisar puede ampliar el área de búsqueda. Si un peligro exige moverte, busca seguridad y comunica el cambio cuando puedas. No tomes una decisión universal basada en que siempre hay que bajar, seguir un río o alcanzar una cima: cada opción puede añadir riesgos.'],
      ['Hazte localizable sin exponerte', 'Ropa visible, silbato y luz pueden ayudar según las condiciones. Mantén el grupo unido si es seguro. No enciendas un fuego para señalizar ni abandones protección adecuada solo para destacar más. Sigue las instrucciones de los equipos cuando lleguen; no te acerques a aeronaves por iniciativa propia.'],
      ['La noche cambia las prioridades', 'Valora frío, viento, lluvia y riesgo de caídas. Protege la ropa seca y evita recorridos improvisados a oscuras. No entres en una cueva desconocida buscando refugio perfecto. Explica al 112 si alguien está lesionado, muy frío, confuso o empeora: la asistencia depende de información actualizada.'],
      ['El rescate se prepara antes de salir', 'Deja a una persona de confianza la ruta, alternativas previstas y hora de regreso. Acuerda qué hacer si no vuelves o no contactas. Consulta meteorología, ajusta dificultad al grupo y lleva agua, abrigo, luz, teléfono cargado y cartografía. Revisa el equipo en casa, no cuando descubras que falta cobertura.'],
      ['Tu prueba para la próxima salida', 'Abre el mapa descargado antes de salir, localiza el inicio y comprueba si sabes consultar coordenadas. No pruebes a perderte ni hagas llamadas de emergencia de ensayo. Si no sabes utilizar un recurso, aprende en un entorno controlado o con formación adecuada. Una ruta más corta y conocida puede ser la mejor elección.'],
    ]), app],
    relatedLinks: [{ label: 'Preparar mapas offline', href: '/supervivencia/como-utilizar-mapas-offline' }],
  },
  {
    ...common, slug: 'sin-mochila-sin-equipo',
    title: 'Supervivencia sin mochila: qué puedes hacer con lo que llevas encima',
    seoTitle: 'Supervivencia sin equipo: recursos y prioridades',
    excerpt: 'Teléfono, ropa, llaves y personas alrededor: aprende a reconocer recursos útiles y elegir el siguiente paso seguro sin depender de una mochila especial.',
    image: '/images/blog/energia-comunicacion-natural.jpg', imageAlt: 'Teléfono y pequeños recursos de comunicación preparados. Imagen ilustrativa.',
    keywords: ['supervivencia sin equipo', 'supervivencia urbana sin mochila', 'emergencia sin material'],
    sections: [...sections([
      ['La emergencia no pregunta si llevas tu kit', 'Muchas listas empiezan por necesitar una radio, manta, filtro y mochila. Pero quizá hoy solo llevas teléfono, cartera y una chaqueta. Antes de pensar en fabricar herramientas, identifica qué ocurre y dónde puedes estar seguro. No estás obligado a resolverlo todo solo: los recursos del entorno también cuentan.'],
      ['Haz inventario sin vaciar los bolsillos en un lugar peligroso', 'Comprueba lo disponible cuando estés seguro. Separa recursos inmediatos, como agua potable o un teléfono operativo, de posibilidades que no has comprobado. Una tienda cerrada no es abastecimiento y una aplicación sin datos guardados no es un mapa offline. Planifica con lo real, no con lo que supones que funcionará.'],
      ['Teléfono: mucho más que mensajería', 'Puede contener contactos, mapas, notas y documentación preparada. Protege batería y dispositivo de golpes y humedad. Comprueba si puedes comunicarte y utiliza emergencias cuando corresponda. No presupongas que una brújula está disponible o calibrada ni que un mapa puede descargarse una vez perdida la red.'],
      ['Ropa: no sacrifiques tu primera protección', 'Ayuda frente al frío, sol y rozaduras. Conservarla seca y ajustarla a las condiciones puede ser más útil que cortarla para un invento. No improvises cuerdas con prendas ni te desprendas del abrigo sin una razón real. Tu movilidad y protección importan más que imitar una técnica de película.'],
      ['Botella: un recurso concreto', 'Si contiene agua potable, sabes qué tienes. Administra las necesidades sin restringir peligrosamente la hidratación. Un recipiente vacío no garantiza que encontrarás agua segura; evita rellenarlo en fuentes desconocidas suponiendo que transparencia equivale a potabilidad.'],
      ['Llaves y cartera: acceso, identidad y alternativas', 'Las llaves pueden dar acceso a recursos propios cuando sea seguro utilizarlos. No vuelvas a un edificio evacuado para recuperarlas. Identificación, contactos mínimos y algo de efectivo pueden ayudar, pero llevar muchos datos sensibles o dinero también introduce riesgos. Guarda lo necesario de forma segura.'],
      ['Mira alrededor: no estás en una isla', 'Personal del lugar, señalización, autoridades y recursos habilitados pueden orientarte. Pide ayuda con claridad y respeta accesos e instrucciones. No entres en instalaciones cerradas ni des por disponible cualquier refugio. En ciudad, cooperar suele ser más útil que tratar de improvisar una vida aislada.'],
      ['Tres preguntas, en este orden', '¿Qué peligro tengo ahora? ¿Qué recursos comprobados tengo encima y cerca? ¿Cuál es el siguiente paso seguro? No intentes resolver veinte problemas hipotéticos antes del riesgo presente. Si las autoridades ordenan confinarse, volver andando a casa no es automáticamente la mejor decisión.'],
      ['Mejora tu día a día, no solo tu mochila', 'Guarda un contacto importante, comprueba la carga y conoce una alternativa al trayecto habitual. Lleva lo que puedas utilizar sin sobrecargarte. La próxima vez que salgas, piensa qué única carencia pequeña puedes resolver. Prepararte empieza por reducir dependencias, no por comprarlo todo.'],
    ]), app],
    relatedLinks: [{ label: 'Volver a casa desde el trabajo', href: '/supervivencia/emergencia-trabajo-volver-casa' }],
  },
  {
    ...common, slug: '5-mitos-de-supervivencia-que-pueden-ponerte-en-peligro',
    title: '15 mitos de supervivencia que el cine nos ha enseñado mal',
    seoTitle: '15 mitos de supervivencia peligrosos del cine',
    excerpt: 'Agua transparente, musgo que señala el norte y héroes que nunca piden ayuda: revisa 15 ideas engañosas antes de convertirlas en decisiones reales.',
    image: '/images/blog/caza-observacion-editorial.jpg', imageAlt: 'Terreno natural que requiere preparación y decisiones prudentes. Imagen ilustrativa.',
    keywords: ['mitos de supervivencia', 'errores supervivencia', 'consejos supervivencia falsos'],
    warning: 'Ante una urgencia sanitaria o necesidad de rescate en España, contacta con el 112. Las instrucciones de profesionales y autoridades prevalecen sobre esta lectura.',
    sources: [mountain, { title: 'NHS: qué no hacer ante una mordedura de serpiente', url: 'https://www.nhs.uk/conditions/snake-bites/' }, { title: 'NWS: seguridad ante rayos al aire libre', url: 'https://www.weather.gov/safety/lightning-outdoors' }],
    sections: [...sections([
      ['La película necesita acción; tú necesitas seguridad', 'Una buena decisión puede parecer aburrida: dar la vuelta a tiempo, pedir ayuda o no cruzar un paso inundado. Estas quince ideas mezclan exageración, información incompleta y errores peligrosos. No son una invitación a probar alternativas en una emergencia; sirven para revisar lo que dabas por aprendido.'],
      ['1. «Si te pierdes, sigue caminando»', 'Caminar sin rumbo puede ampliar la zona de búsqueda. Detente en un lugar seguro, evalúa y contacta con emergencias si necesitas ayuda. Si te indican permanecer, no cambies de posición sin necesidad; un peligro inmediato puede exigir moverte y comunicarlo.'],
      ['2. «Beber orina resuelve la falta de agua»', 'No la utilices como estrategia de hidratación. La preparación debe centrarse en agua potable y fuentes seguras previstas, no en reciclar líquidos de desecho. Si la falta de agua compromete tu salud, pide ayuda antes de empeorar.'],
      ['3. «El agua transparente es potable»', 'La apariencia no permite descartar microorganismos ni contaminantes químicos. Un tratamiento tiene límites y debe corresponder al riesgo. No improvises con agua de inundaciones, vertidos o fuentes desconocidas.'],
      ['4. «El musgo siempre señala el norte»', 'Humedad, sombra y condiciones locales influyen en su crecimiento. No lo conviertas en brújula. Prepara cartografía y herramientas que sepas utilizar; si no puedes orientarte, caminar siguiendo una suposición no resuelve el problema.'],
      ['5. «Hay que succionar el veneno»', 'No cortes ni succiones una mordedura de serpiente. Solicita asistencia urgente y sigue instrucciones. No intentes capturar al animal ni pongas en peligro a otra persona para identificarlo.'],
      ['6. «El alcohol sirve para calentarse»', 'No lo uses como tratamiento frente al frío. La sensación de calor no demuestra que estés protegido. Prioriza protección adecuada y asistencia si hay deterioro; evita decisiones y desplazamientos bajo sus efectos.'],
      ['7. «Comer nieve es igual que beber agua»', 'No planifiques tu hidratación dependiendo de comer nieve. También existe riesgo de contaminación y enfriamiento. Lleva agua segura y medios adecuados al recorrido; derretir nieve no demuestra por sí solo que sea potable.'],
      ['8. «Lo primero siempre es encontrar comida»', 'En una emergencia corta pueden ser más urgentes el peligro inmediato, abrigo, agua, comunicación y rescate. Las necesidades médicas particulares importan. No abandones un lugar seguro para buscar alimentos silvestres que no sabes identificar.'],
      ['9. «Un fuego grande siempre es mejor»', 'Consume más recursos y puede convertirse en otro incendio. No enciendas fuego por reflejo ni para demostrar una habilidad. Respeta prohibiciones y condiciones; para señalización e iluminación prepara alternativas sin llama.'],
      ['10. «Cualquier cueva es un buen refugio»', 'Puede ocultar desniveles, agua y otros peligros. No explores una cavidad desconocida ni supongas que la entrada protege de rayos. Elige refugios previstos y consulta a emergencias si necesitas orientación.'],
      ['11. «Un árbol grande protege de la tormenta»', 'Un árbol aislado no es un refugio seguro frente a rayos. Busca un edificio adecuado o un vehículo cerrado apropiado cuando puedas alcanzarlo con seguridad. Una tienda de campaña no proporciona esa protección.'],
      ['12. «Un todoterreno atraviesa cualquier inundación»', 'No puedes valorar bien corriente, profundidad o daños del firme. No cruces zonas inundadas ni sortees cierres. El vehículo no convierte una ruta cortada en una alternativa segura.'],
      ['13. «Grita sin parar para que te encuentren»', 'Puedes agotarte sin mejorar la localización. Un silbato y señales visibles pueden ayudar si las condiciones lo permiten. Conserva energía y sigue el plan indicado por rescate, sin ponerte en peligro para destacar.'],
      ['14. «El fuerte actúa solo»', 'Repartir tareas e información puede mejorar la respuesta. Comunica limitaciones y necesidades; pedir ayuda a tiempo no es un fracaso. No separes al grupo para demostrar autosuficiencia ni asignes tareas peligrosas sin preparación.'],
      ['15. «Sobrevivir exige hacer algo espectacular»', 'Consultar el tiempo, avisar de la ruta, cargar el teléfono y renunciar a un paso peligroso son decisiones poco cinematográficas y muy útiles. El objetivo es evitar que un problema pequeño crezca, no conseguir una historia heroica.'],
      ['Comprueba una creencia antes de tu próxima salida', 'Elige una idea que dabas por segura y contrástala en una fuente oficial. Revisa después un recurso práctico: agua, contacto, mapa o luz. Aprender también significa reconocer cuándo una técnica no debe intentarse.'],
    ]), app],
    relatedLinks: [{ label: 'Qué hacer si te pierdes', href: '/supervivencia/que-hacer-si-te-pierdes-24-horas' }],
  },
];
