import type { FaqItem } from "@/types/content";

export const faqs: FaqItem[] = [
  ["¿La aplicación funciona sin Internet?", "Aproximadamente el 99 % de contenidos y herramientas está pensado para funcionar sin conexión una vez instalado y preparado."],
  ["¿Qué funciones necesitan conexión?", "Meteorología actualizada, alertas actualizadas, descargas iniciales, mapas adicionales, modelos de IA, actualizaciones y cualquier integración externa configurada."],
  ["¿Está disponible para Android?", "Sí, la web está preparada para ofrecer descarga mediante APK para Android."],
  ["¿Cómo se instala el APK?", "Desde la página Descargar se indican los pasos para instalarlo desde la web oficial y revisar permisos."],
  ["¿Es seguro instalar la aplicación?", "Debe instalarse solo desde la web oficial y verificarse el hash SHA-256 cuando esté publicado. El hash está pendiente de añadir."],
  ["¿Dónde se guardan mis datos?", "La configuración indica almacenamiento local para funciones personales. Cualquier exportación o compartición requiere acción del usuario."],
  ["¿La Caja Negra se activa automáticamente?", "Solo si el usuario la configura y autoriza previamente dentro de la aplicación."],
  ["¿La aplicación graba sin permiso?", "No debe hacerlo. Las funciones de cámara, micrófono o ubicación requieren autorización previa del usuario."],
  ["¿Puedo importar mapas?", "Sí, la aplicación está preparada para importar mapas compatibles en formato MBTiles."],
  ["¿Qué es un archivo MBTiles?", "Es un contenedor de mapas en mosaicos que puede almacenarse localmente para consulta offline."],
  ["¿Puedo utilizar mapas de otros países?", "Sí, si el archivo es compatible y respeta las licencias cartográficas."],
  ["¿La aplicación sustituye al 112?", "No. Ante una emergencia real, llama al 112 siempre que sea posible y sigue las instrucciones oficiales."],
  ["¿La aplicación sustituye a un médico?", "No. No realiza diagnósticos ni sustituye atención médica, sanitaria o psicológica."],
  ["¿La IA offline puede equivocarse?", "Sí. Puede equivocarse, inventar información o funcionar lentamente según el dispositivo y el modelo."],
  ["¿Puedo exportar mi plan familiar?", "La estructura contempla exportación, compartir e importación entre dispositivos cuando la función esté disponible en la app."],
  ["¿Puedo guardar documentación?", "Sí, con advertencias sobre datos sensibles y protección del dispositivo."],
  ["¿Puedo eliminar mis datos?", "La web documenta que los registros y datos locales deben poder revisarse y borrarse desde la aplicación."],
  ["¿La aplicación incluye publicidad?", "Configurar antes de publicar."],
  ["¿Tiene compras?", "Configurar antes de publicar."],
  ["¿Cómo se actualiza?", "Descargando la nueva versión oficial del APK o mediante el sistema que se configure en el futuro."],
  ["¿Qué permisos necesita?", "Depende de las funciones activadas: ubicación, cámara, micrófono, archivos y notificaciones son permisos posibles."],
  ["¿Funciona en todos los teléfonos?", "No se puede garantizar. Depende de Android, sensores, memoria, almacenamiento y compatibilidad del dispositivo."],
  ["¿Cuánto espacio ocupa?", "Pendiente de añadir; también dependerá de mapas, documentos, modelos y recursos opcionales."],
  ["¿Dónde puedo comunicar un error?", "Añadir correo de soporte o formulario configurado antes de publicar."],
  ["¿Cómo verifico que el APK es original?", "Compara el hash SHA-256 publicado en la web con el hash calculado del archivo descargado."],
].map(([question, answer]) => ({ question, answer }));
