import type { AppFeature } from "@/types/content";

export const features: AppFeature[] = [
  {
    id: "crisis-mode",
    slug: "modo-crisis",
    title: "Modo Crisis",
    shortDescription: "Escenarios rápidos con prioridades, riesgos y primeras acciones.",
    fullDescription:
      "Permite seleccionar la emergencia y consultar instrucciones concretas desde una pantalla pensada para momentos de presión.",
    icon: "Siren",
    availability: "offline",
    category: "Emergencia",
    highlights: ["Apagón", "Sin cobertura", "Evacuación", "Crisis personalizadas"],
  },
  {
    id: "sos",
    slug: "seguridad",
    title: "Botón SOS",
    shortDescription: "Accesos rápidos a 112, coordenadas, señales y Caja Negra autorizada.",
    fullDescription:
      "Centraliza ayuda esencial sin prometer avisos automáticos a emergencias. Ante una emergencia real, llama al 112 siempre que sea posible.",
    icon: "LifeBuoy",
    availability: "hybrid",
    category: "Emergencia",
    highlights: ["112", "Coordenadas GPS", "Señales", "Consejos esenciales"],
    warnings: ["No sustituye al 112 ni a los servicios de emergencia."],
  },
  {
    id: "maps",
    slug: "mapas-offline",
    title: "Mapas offline",
    shortDescription: "Compatibilidad con mapas MBTiles almacenados en el dispositivo.",
    fullDescription:
      "Consulta mapas locales, importa archivos MBTiles, guarda puntos y trabaja aunque no haya mapas online.",
    icon: "Map",
    availability: "offline",
    category: "Orientación",
    highlights: ["MBTiles", "Puntos guardados", "Pantalla completa", "Mapas por categoría"],
  },
  {
    id: "guides",
    slug: "guias-supervivencia",
    title: "Más de 300 guías",
    shortDescription: "Biblioteca preparada para artículos de supervivencia y preparación.",
    fullDescription:
      "Estructura con buscador, favoritos, filtros y categorías para incorporar progresivamente todos los contenidos.",
    icon: "BookOpen",
    availability: "offline",
    category: "Conocimiento",
    highlights: ["Agua", "Primeros auxilios", "Fuego", "Orientación"],
  },
  {
    id: "family",
    slug: "preparacion-familiar",
    title: "Preparación familiar",
    shortDescription: "Planes, roles, rutas, puntos de encuentro, simulacros y progreso.",
    fullDescription:
      "Ayuda a organizar a la familia antes de una emergencia con datos editables y exportables.",
    icon: "Users",
    availability: "offline",
    category: "Planificación",
    highlights: ["Plan familiar", "Roles", "Retos", "Simulacros"],
  },
  {
    id: "calculators",
    slug: "herramientas-supervivencia",
    title: "Calculadoras",
    shortDescription: "Agua, energía, potabilización, hipotermia, conversiones y más.",
    fullDescription:
      "Calculadoras orientativas con advertencias claras para evitar decisiones de riesgo basadas en una cifra.",
    icon: "Calculator",
    availability: "offline",
    category: "Herramientas",
    highlights: ["Agua", "Energía", "Ríos", "Hipotermia"],
  },
  {
    id: "black-box",
    slug: "seguridad",
    title: "Caja Negra",
    shortDescription: "Registros locales configurables de ubicación, audio o vídeo.",
    fullDescription:
      "Solo funciona cuando el usuario la autoriza y configura previamente. Los registros pueden revisarse y eliminarse.",
    icon: "ShieldCheck",
    availability: "offline",
    category: "Seguridad",
    highlights: ["15, 30 o 60 segundos", "Consentimiento", "Borrado", "Uso desde SOS"],
  },
  {
    id: "offline-ai",
    slug: "ia-enciclopedia",
    title: "IA offline",
    shortDescription: "Asistente local cuando el dispositivo y el modelo son compatibles.",
    fullDescription:
      "Puede procesar consultas en el dispositivo, con limitaciones de precisión, rendimiento, batería y compatibilidad.",
    icon: "Cpu",
    availability: "offline",
    category: "Tecnología",
    highlights: ["Modelo local", "Sin Internet", "Privacidad mejorada", "Limitaciones visibles"],
    warnings: ["La IA puede equivocarse o inventar información."],
  },
  {
    id: "academy",
    slug: "aprendizaje-supervivencia",
    title: "Academia Survival",
    shortDescription: "Lecciones, preguntas, progreso, mitos peligrosos y aprendizaje familiar.",
    fullDescription:
      "Convierte la preparación en aprendizaje progresivo con contenidos para adultos, familia y menores.",
    icon: "GraduationCap",
    availability: "offline",
    category: "Aprendizaje",
    highlights: ["Preguntas", "Retos", "Repaso", "Juego 72 horas"],
  },
  {
    id: "plants",
    slug: "ia-enciclopedia",
    title: "Plantas, animales y hongos",
    shortDescription: "Fichas editables con advertencias de identificación y riesgo.",
    fullDescription:
      "Estructura para fotografías, hábitat, época, confusiones y riesgos, sin recomendar consumo solo por una app.",
    icon: "Leaf",
    availability: "offline",
    category: "Naturaleza",
    highlights: ["España", "Filtros", "Riesgos", "Fotografías"],
  },
  {
    id: "vehicle",
    slug: "herramientas-supervivencia",
    title: "Vehículo",
    shortDescription: "Kits y escenarios de avería, nieve, riadas, túneles y eléctricos.",
    fullDescription:
      "Prioriza seguridad, señalización y llamada a emergencias, evitando instrucciones técnicamente peligrosas.",
    icon: "Car",
    availability: "offline",
    category: "Movilidad",
    highlights: ["Kit coche", "Averías", "Nieve", "Vehículo eléctrico"],
  },
  {
    id: "alerts",
    slug: "con-uso-de-internet",
    title: "Alertas y meteorología",
    shortDescription: "Información actualizada cuando hay conexión y fuentes disponibles.",
    fullDescription:
      "Muestra avisos y previsión cuando se descargan datos. Sin conexión conserva la última información, que puede estar desactualizada.",
    icon: "CloudSun",
    availability: "online",
    category: "Información",
    highlights: ["Alertas", "Tiempo", "Última previsión", "Fuentes externas"],
    warnings: ["No sustituye ES-Alert ni Protección Civil."],
  },
];
