import type { AppFeature } from "@/types/content";

export const features: AppFeature[] = [
  {
    id: "crisis-mode",
    slug: "modo-crisis",
    title: "Modo Crisis",
    shortDescription: "Escenarios rÃƒÆ’Ã‚Â¡pidos con prioridades, riesgos y primeras acciones.",
    fullDescription:
      "Permite seleccionar la emergencia y consultar instrucciones concretas desde una pantalla pensada para momentos de presiÃƒÆ’Ã‚Â³n.",
    icon: "Siren",
    availability: "offline",
    category: "Emergencia",
    highlights: ["ApagÃƒÆ’Ã‚Â³n", "Sin cobertura", "EvacuaciÃƒÆ’Ã‚Â³n", "Crisis personalizadas"],
  },
  {
    id: "sos",
    slug: "seguridad",
    title: "BotÃƒÆ’Ã‚Â³n SOS",
    shortDescription: "Accesos rÃƒÆ’Ã‚Â¡pidos a 112, coordenadas, seÃƒÆ’Ã‚Â±ales y Caja Negra autorizada.",
    fullDescription:
      "Centraliza ayuda esencial sin prometer avisos automÃƒÆ’Ã‚Â¡ticos a emergencias. Ante una emergencia real, llama al 112 siempre que sea posible.",
    icon: "LifeBuoy",
    availability: "hybrid",
    category: "Emergencia",
    highlights: ["112", "Coordenadas GPS", "SeÃƒÆ’Ã‚Â±ales", "Consejos esenciales"],
    warnings: ["No sustituye al 112 ni a los servicios de emergencia."],
  },
  {
    id: "maps",
    slug: "mapas-offline",
    title: "Mapas offline",
    shortDescription: "Compatibilidad con mapas MBTiles almacenados en el dispositivo.",
    fullDescription:
      "Consulta mapas locales, importa archivos MBTiles, guarda puntos y trabaja aunque no haya mapas online.",
    icon: "Map",
    availability: "offline",
    category: "OrientaciÃƒÆ’Ã‚Â³n",
    highlights: ["MBTiles", "Puntos guardados", "Pantalla completa", "Mapas por categorÃƒÆ’Ã‚Â­a"],
  },
  {
    id: "guides",
    slug: "guias-supervivencia",
    title: "MÃƒÆ’Ã‚Â¡s de 300 guÃƒÆ’Ã‚Â­as",
    shortDescription: "Biblioteca preparada para artÃƒÆ’Ã‚Â­culos de supervivencia y preparaciÃƒÆ’Ã‚Â³n.",
    fullDescription:
      "Estructura con buscador, favoritos, filtros y categorÃƒÆ’Ã‚Â­as para incorporar progresivamente todos los contenidos.",
    icon: "BookOpen",
    availability: "offline",
    category: "Conocimiento",
    highlights: ["Agua", "Primeros auxilios", "Fuego", "OrientaciÃƒÆ’Ã‚Â³n"],
  },
  {
    id: "family",
    slug: "preparacion-familiar",
    title: "Herramientas",
    shortDescription: "Planes, roles, rutas, puntos de encuentro, simulacros y progreso.",
    fullDescription:
      "Ayuda a organizar a la familia antes de una emergencia con datos editables y exportables.",
    icon: "Users",
    availability: "offline",
    category: "PlanificaciÃƒÆ’Ã‚Â³n",
    highlights: ["Plan familiar", "Roles", "Retos", "Simulacros"],
  },
  {
    id: "calculators",
    slug: "recursos-avanzados",
    title: "Calculadoras",
    shortDescription: "Agua, energÃƒÆ’Ã‚Â­a, potabilizaciÃƒÆ’Ã‚Â³n, hipotermia, conversiones y mÃƒÆ’Ã‚Â¡s.",
    fullDescription:
      "Calculadoras orientativas con advertencias claras para evitar decisiones de riesgo basadas en una cifra.",
    icon: "Calculator",
    availability: "offline",
    category: "Herramientas",
    highlights: ["Agua", "EnergÃƒÆ’Ã‚Â­a", "RÃƒÆ’Ã‚Â­os", "Hipotermia"],
  },
  {
    id: "black-box",
    slug: "seguridad",
    title: "Caja Negra",
    shortDescription: "Registros locales configurables de ubicaciÃƒÆ’Ã‚Â³n, audio o vÃƒÆ’Ã‚Â­deo.",
    fullDescription:
      "Solo funciona cuando el usuario la autoriza y configura previamente. Los registros pueden revisarse y eliminarse.",
    icon: "ShieldCheck",
    availability: "offline",
    category: "Seguridad",
    highlights: ["15, 30 o 60 segundos", "Consentimiento", "Borrado", "Uso desde SOS"],
  },
  {
    id: "offline-ai",
    slug: "ia-enciclopedia",
    title: "IA offline",
    shortDescription: "Asistente local cuando el dispositivo y el modelo son compatibles.",
    fullDescription:
      "Puede procesar consultas en el dispositivo, con limitaciones de precisiÃƒÆ’Ã‚Â³n, rendimiento, baterÃƒÆ’Ã‚Â­a y compatibilidad.",
    icon: "Cpu",
    availability: "offline",
    category: "TecnologÃƒÆ’Ã‚Â­a",
    highlights: ["Modelo local", "Sin Internet", "Privacidad mejorada", "Limitaciones visibles"],
    warnings: ["La IA puede equivocarse o inventar informaciÃƒÆ’Ã‚Â³n."],
  },
  {
    id: "academy",
    slug: "aprendizaje-supervivencia",
    title: "Academia Survival",
    shortDescription: "Lecciones, preguntas, progreso, mitos peligrosos y aprendizaje familiar.",
    fullDescription:
      "Convierte la preparaciÃƒÆ’Ã‚Â³n en aprendizaje progresivo con contenidos para adultos, familia y menores.",
    icon: "GraduationCap",
    availability: "offline",
    category: "Aprendizaje",
    highlights: ["Preguntas", "Retos", "Repaso", "Juego 72 horas"],
  },
  {
    id: "plants",
    slug: "ia-enciclopedia",
    title: "Plantas, animales y hongos",
    shortDescription: "Fichas editables con advertencias de identificaciÃƒÆ’Ã‚Â³n y riesgo.",
    fullDescription:
      "Estructura para fotografÃƒÆ’Ã‚Â­as, hÃƒÆ’Ã‚Â¡bitat, ÃƒÆ’Ã‚Â©poca, confusiones y riesgos, sin recomendar consumo solo por una app.",
    icon: "Leaf",
    availability: "offline",
    category: "Naturaleza",
    highlights: ["EspaÃƒÆ’Ã‚Â±a", "Filtros", "Riesgos", "FotografÃƒÆ’Ã‚Â­as"],
  },
  {
    id: "vehicle",
    slug: "recursos-avanzados",
    title: "VehÃƒÆ’Ã‚Â­culo",
    shortDescription: "Kits y escenarios de averÃƒÆ’Ã‚Â­a, nieve, riadas, tÃƒÆ’Ã‚Âºneles y elÃƒÆ’Ã‚Â©ctricos.",
    fullDescription:
      "Prioriza seguridad, seÃƒÆ’Ã‚Â±alizaciÃƒÆ’Ã‚Â³n y llamada a emergencias, evitando instrucciones tÃƒÆ’Ã‚Â©cnicamente peligrosas.",
    icon: "Car",
    availability: "offline",
    category: "Movilidad",
    highlights: ["Kit coche", "AverÃƒÆ’Ã‚Â­as", "Nieve", "VehÃƒÆ’Ã‚Â­culo elÃƒÆ’Ã‚Â©ctrico"],
  },
  {
    id: "alerts",
    slug: "con-uso-de-internet",
    title: "Alertas y meteorologÃƒÆ’Ã‚Â­a",
    shortDescription: "InformaciÃƒÆ’Ã‚Â³n actualizada cuando hay conexiÃƒÆ’Ã‚Â³n y fuentes disponibles.",
    fullDescription:
      "Muestra avisos y previsiÃƒÆ’Ã‚Â³n cuando se descargan datos. Sin conexiÃƒÆ’Ã‚Â³n conserva la ÃƒÆ’Ã‚Âºltima informaciÃƒÆ’Ã‚Â³n, que puede estar desactualizada.",
    icon: "CloudSun",
    availability: "online",
    category: "InformaciÃƒÆ’Ã‚Â³n",
    highlights: ["Alertas", "Tiempo", "ÃƒÆ’Ã…Â¡ltima previsiÃƒÆ’Ã‚Â³n", "Fuentes externas"],
    warnings: ["No sustituye ES-Alert ni ProtecciÃƒÆ’Ã‚Â³n Civil."],
  },
];
