import type { GuideCategory } from "@/types/content";

export const guideCategories: GuideCategory[] = [
  {
    id: "agua",
    title: "Agua",
    description: "Guías para calcular reservas, almacenar agua y actuar cuando el suministro falla.",
    articleCountLabel: "11 artículos offline",
    expansion: "Ayuda a saber cuánta agua guardar, cómo repartirla entre beber, higiene y cocina, y qué métodos son más adecuados según el estado del agua.",
    articleExamples: ["Cuánta agua necesita una persona", "Cómo almacenar agua en casa", "Potabilizar agua por hervido", "Pastillas potabilizadoras", "Agua turbia o contaminada"],
    usageTips: ["Abre la guía completa y entra en Agua antes de una emergencia para calcular tus reservas.", "Marca la estrella para que Agua aparezca en la pantalla principal."],
  },
  {
    id: "alimentacion",
    title: "Alimentación",
    description: "Artículos para organizar comida, priorizar consumo y cocinar cuando no hay electricidad.",
    articleCountLabel: "7 artículos offline",
    expansion: "Sirve para preparar una despensa realista, reducir pérdidas durante apagones y planificar comidas sencillas con recursos limitados.",
    articleExamples: ["Despensa de emergencia", "Orden de consumo en emergencia", "Cocinar sin electricidad", "Gestión de nevera en apagón", "Recetas sin electricidad"],
    usageTips: ["Revisa esta categoría al preparar inventario y checklists.", "Combínala con agua y energía para calcular autonomía familiar."],
  },
  {
    id: "primeros-auxilios",
    title: "Primeros auxilios",
    description: "Protocolos básicos de actuación y material sanitario para emergencias habituales.",
    articleCountLabel: "16 artículos offline",
    expansion: "Incluye guías de apoyo para reconocer señales de riesgo, organizar el botiquín y saber cuándo pedir ayuda profesional. No sustituye atención médica.",
    articleExamples: ["Botiquín básico de emergencia", "Cómo controlar una hemorragia", "Quemaduras: tratamiento básico", "Fracturas y esguinces", "Golpe de calor e hipotermia"],
    usageTips: ["Úsala como repaso previo y como consulta rápida, no como diagnóstico.", "Guarda también tus datos médicos en Salud si los necesitas offline."],
  },
  {
    id: "fuego",
    title: "Fuego",
    description: "Uso seguro del fuego, calor de emergencia y prevención de intoxicaciones.",
    articleCountLabel: "15 artículos offline",
    expansion: "La categoría explica cómo reducir riesgos al usar calor, cómo apagar correctamente y qué peligros invisibles vigilar, como el monóxido de carbono.",
    articleExamples: ["Cómo hacer fuego de forma segura", "Cómo apagar un fuego correctamente", "Monóxido de carbono", "Hacer fuego sin mechero", "Calor seguro en refugio"],
    usageTips: ["Consulta siempre las advertencias antes de encender fuego.", "Prioriza ventilación y seguridad frente a cualquier técnica."],
  },
  {
    id: "refugios",
    title: "Refugios",
    description: "Preparación de casa, aislamiento, calor y refugios temporales de emergencia.",
    articleCountLabel: "13 artículos offline",
    expansion: "Ayuda a convertir la vivienda o un punto temporal en un lugar más seguro, seco y cálido mientras llega ayuda o se decide evacuar.",
    articleExamples: ["Refugio en casa: protección y calor", "Conservar calor en emergencia", "Plan de evacuación del hogar", "Refugio temporal con lona", "Aislamiento básico"],
    usageTips: ["Úsala junto al plan familiar para decidir si quedarse o salir.", "Marca los artículos importantes como favoritos."],
  },
  {
    id: "orientacion",
    title: "Orientación",
    description: "Brújula, coordenadas, puntos guardados y métodos sencillos para no desorientarse.",
    articleCountLabel: "9 artículos offline",
    expansion: "Explica cómo orientarte sin mapas online, guardar ubicaciones importantes y volver a puntos conocidos usando brújula, GPS y referencias naturales.",
    articleExamples: ["Brújula y orientación", "Orientarse con el sol", "Método del reloj", "Guardar posición GPS", "Volver a un punto guardado"],
    usageTips: ["Guarda casa, vehículo y punto de encuentro antes de necesitarlos.", "Comprueba permisos y sensores del teléfono."],
  },
  {
    id: "comunicacion",
    title: "Comunicación",
    description: "Señales, Morse, silbato, humo, radio y comunicación local sin Internet.",
    articleCountLabel: "7 artículos offline",
    expansion: "Reúne métodos para pedir ayuda, coordinarse con otras personas y transmitir información cuando no hay datos móviles.",
    articleExamples: ["Señales SOS", "Código Morse", "Silbatos de emergencia", "Señales de humo", "Bluetooth y Wi-Fi Direct"],
    usageTips: ["Aprende señales cortas antes de una salida o viaje.", "Recuerda que ninguna señal garantiza recepción."],
  },
  {
    id: "seguridad-familiar",
    title: "Seguridad familiar",
    description: "Organización de miembros, roles, contactos alternativos y simulacros familiares.",
    articleCountLabel: "Guía familiar ampliada",
    expansion: "Está pensada para que cada persona sepa qué hacer, dónde reunirse y a quién llamar si la familia se separa o falla la comunicación.",
    articleExamples: ["Roles familiares", "Puntos de encuentro", "Contactos alternativos", "Plan para menores", "Simulacros sin asustar"],
    usageTips: ["Completa el plan familiar desde la app.", "Practica rutas y puntos de encuentro de forma tranquila."],
  },
  {
    id: "hogar-preparado",
    title: "Hogar preparado",
    description: "Revisiones, suministros, cortes de luz, cortes de agua y preparación doméstica.",
    articleCountLabel: "Preparación del hogar",
    expansion: "Convierte la preparación en tareas concretas: revisar botiquín, alimentos, pilas, agua, documentos y zonas seguras de la vivienda.",
    articleExamples: ["Casa preparada para emergencias", "Apagón prolongado", "Corte de agua", "Kit de invierno y calor", "Revisión mensual"],
    usageTips: ["Pasa esta categoría a favoritos si estás preparando la casa.", "Úsala con inventario y checklists."],
  },
  {
    id: "supervivencia-con-vehiculo",
    title: "Supervivencia con vehículo",
    description: "Kit de coche y escenarios de avería, accidente, nieve, túnel o inundación.",
    articleCountLabel: "11 escenarios",
    expansion: "Prioriza señalización, autoprotección y llamada a emergencias. No incluye maniobras peligrosas ni instrucciones irresponsables.",
    articleExamples: ["Kit supervivencia coche", "Avería en zona aislada", "Atrapado en nieve", "Accidente de tráfico", "Inundación o riada"],
    usageTips: ["Revisa el kit del vehículo cada temporada.", "Guarda la ubicación del coche cuando aparques en zonas desconocidas."],
  },
  {
    id: "energia",
    title: "Energía",
    description: "Batería, powerbanks, ahorro extremo y consumo de dispositivos esenciales.",
    articleCountLabel: "Autonomía orientativa",
    expansion: "Ayuda a decidir qué apagar, cuándo cargar, cómo priorizar el teléfono y cuánto pueden durar tus baterías externas.",
    articleExamples: ["Control de batería", "Calculadora de powerbank", "Ahorro moderado", "Ahorro alto", "Ultra emergencia"],
    usageTips: ["Usa la calculadora de energía para estimar cargas.", "Reduce brillo, conexiones y apps antes de quedarte sin batería."],
  },
  {
    id: "supervivencia-urbana",
    title: "Supervivencia urbana",
    description: "Emergencias graves en ciudad, falta de suministros, evacuación y seguridad.",
    articleCountLabel: "16 artículos offline",
    expansion: "Explica cómo actuar en un piso, barrio o ciudad cuando fallan servicios, transporte, agua, electricidad o comunicaciones.",
    articleExamples: ["Apagón prolongado en ciudad", "Sobrevivir 72 horas en un piso", "Plan de evacuación urbana", "Conseguir agua segura en ciudad", "Abastecimiento responsable"],
    usageTips: ["Adapta los consejos a tu vivienda y barrio.", "Evita siempre enfrentamientos y sigue instrucciones oficiales."],
  },
  {
    id: "catastrofes-en-espana",
    title: "Catástrofes en España",
    description: "Guías adaptadas a riesgos frecuentes en España y recomendaciones oficiales.",
    articleCountLabel: "Escenarios por riesgo",
    expansion: "Organiza cada escenario en antes, durante y después, con material recomendado, errores a evitar y cuándo llamar al 112.",
    articleExamples: ["DANA e inundación", "Incendio forestal", "Ola de calor", "Ola de frío", "Tormenta eléctrica"],
    usageTips: ["Consulta fuentes oficiales cuando haya conexión.", "Guarda las fichas críticas como favoritas."],
  },
  {
    id: "psicologia-y-estres",
    title: "Psicología y estrés",
    description: "Técnicas breves para recuperar calma, ordenar prioridades y ayudar a menores.",
    articleCountLabel: "Apoyo emocional",
    expansion: "Incluye recursos de apoyo como respiración, técnica STOP y 5-4-3-2-1. No sustituye atención psicológica o médica.",
    articleExamples: ["Mantener la calma", "Técnica de un minuto", "Técnica STOP", "5-4-3-2-1", "Cómo hablar con niños"],
    usageTips: ["Practica las técnicas antes de necesitarlas.", "Úsalas como apoyo, no como tratamiento."],
  },
  {
    id: "higiene-y-salud",
    title: "Higiene y salud",
    description: "Higiene con pocos recursos, medicación, alergias y datos sanitarios importantes.",
    articleCountLabel: "Salud offline",
    expansion: "Ayuda a mantener rutinas básicas de higiene, conservar medicación y tener información sanitaria disponible en el dispositivo.",
    articleExamples: ["Higiene con poca agua", "Medicamentos importantes", "Alergias", "Datos médicos", "Prevención de infecciones"],
    usageTips: ["Actualiza tus datos de salud periódicamente.", "Protege el teléfono si guardas información sensible."],
  },
  {
    id: "supervivencia-en-montana",
    title: "Supervivencia en montaña",
    description: "Orientación, frío, refugio, señalización y regreso seguro en zonas aisladas.",
    articleCountLabel: "Montaña y exterior",
    expansion: "Está orientada a evitar desorientación, hipotermia, agotamiento y decisiones de riesgo durante rutas o actividades al aire libre.",
    articleExamples: ["Perdido en la montaña", "Señales para rescate", "Frío e hipotermia", "Agua en ruta", "Punto de regreso"],
    usageTips: ["Descarga mapas antes de salir.", "Comparte ruta y hora prevista con alguien de confianza."],
  },
  {
    id: "campamento-y-exterior",
    title: "Campamento y exterior",
    description: "Campamento básico, refugio temporal, cocina exterior, agua y seguridad.",
    articleCountLabel: "Exterior práctico",
    expansion: "Reúne artículos para montar un entorno básico seguro sin convertir la app en una guía de riesgo o aventura extrema.",
    articleExamples: ["Zona de campamento segura", "Refugio temporal", "Cocina exterior", "Gestión de residuos", "Protección contra frío y calor"],
    usageTips: ["Comprueba normativa local antes de hacer fuego.", "Deja ubicaciones guardadas si te mueves por etapas."],
  },
  {
    id: "guias-para-ninos",
    title: "Guías para niños",
    description: "Contenido familiar para enseñar calma, 112, puntos seguros y normas simples.",
    articleCountLabel: "Modo niño",
    expansion: "Usa un tono no aterrador para que los menores aprendan qué hacer, qué evitar y cómo pedir ayuda.",
    articleExamples: ["Cuándo llamar al 112", "No tocar cables", "Buscar un adulto de confianza", "Recordar nombre y teléfono", "Seguir el plan familiar"],
    usageTips: ["Practícalo como juego familiar.", "Evita explicaciones alarmistas."],
  },
  {
    id: "guias-para-personas-mayores",
    title: "Guías para personas mayores",
    description: "Preparación adaptada a medicación, movilidad, contactos y necesidades especiales.",
    articleCountLabel: "Apoyo familiar",
    expansion: "Ayuda a preparar rutinas sencillas para personas con medicación, movilidad reducida o necesidad de contacto frecuente.",
    articleExamples: ["Medicación y alergias", "Contactos visibles", "Documentación médica", "Puntos de encuentro", "Evacuación con movilidad limitada"],
    usageTips: ["Guarda información médica actualizada.", "Comprueba que los textos se leen bien en el dispositivo."],
  },
  {
    id: "seguridad-personal",
    title: "Seguridad personal",
    description: "Prevención, discreción, puntos seguros y decisiones prudentes en emergencias.",
    articleCountLabel: "Prevención responsable",
    expansion: "Prioriza evitar riesgos, mantenerse visible para ayuda y seguir instrucciones oficiales, sin promover confrontaciones.",
    articleExamples: ["Evitar zonas de riesgo", "Moverse con discreción", "Puntos seguros", "Comunicación con familiares", "Cuándo evacuar"],
    usageTips: ["No uses la app para exponerte a situaciones peligrosas.", "Ante riesgo real, llama al 112 si es posible."],
  },
  {
    id: "plantas-y-animales",
    title: "Plantas y animales",
    description: "Fichas informativas sobre especies útiles, peligrosas y riesgos sanitarios.",
    articleCountLabel: "Identificación prudente",
    expansion: "Incluye advertencias claras: nunca consumas plantas, hongos o animales solo por una foto o una descripción.",
    articleExamples: ["Plantas peligrosas", "Plantas comestibles", "Hongos peligrosos", "Animales peligrosos", "Riesgos sanitarios"],
    usageTips: ["Usa la información para evitar riesgos, no para consumir especies dudosas.", "Contrasta siempre con expertos o fuentes oficiales."],
  },
  {
    id: "desastres-naturales",
    title: "Desastres naturales",
    description: "Antes, durante y después de DANA, terremotos, incendios, tormentas y temperaturas extremas.",
    articleCountLabel: "Guías por desastre",
    expansion: "Cada ficha organiza acciones previas, actuación durante la crisis, recuperación, material recomendado y errores que conviene evitar.",
    articleExamples: ["Inundación / DANA", "Terremoto", "Incendio forestal", "Tormenta eléctrica", "Nevada"],
    usageTips: ["Lee el apartado antes de la temporada de riesgo.", "Sigue siempre Protección Civil y avisos oficiales."],
  },
  {
    id: "habilidades-outdoor",
    title: "Habilidades outdoor",
    description: "Técnicas básicas de exterior: señalización, orientación, nudos y refugio.",
    articleCountLabel: "Habilidades prácticas",
    expansion: "Agrupa habilidades útiles para rutas, campamento y situaciones aisladas, siempre con enfoque de seguridad.",
    articleExamples: ["Señalización visual", "Lectura básica del terreno", "Nudos útiles", "Refugio rápido", "Gestión de frío y calor"],
    usageTips: ["Practica en condiciones seguras.", "No improvises técnicas críticas en una emergencia real."],
  },
  {
    id: "caza-de-supervivencia",
    title: "Caza de supervivencia",
    description: "Contenido educativo sobre rastros, riesgos sanitarios, seguridad y legislación.",
    articleCountLabel: "Legal y responsable",
    expansion: "No fomenta caza furtiva ni métodos crueles. Recuerda licencias, vedas, especies protegidas y normativa aplicable.",
    articleExamples: ["Huellas y rastros", "Comportamiento animal", "Riesgos sanitarios", "Legislación", "Manipulación responsable"],
    usageTips: ["Comprueba la normativa antes de cualquier actividad.", "Usa las fichas para aprender rastros y seguridad."],
  },
  {
    id: "pesca-de-supervivencia",
    title: "Pesca de supervivencia",
    description: "Evaluación del agua, técnicas básicas, nudos, limpieza y normativa.",
    articleCountLabel: "Pesca responsable",
    expansion: "Explica riesgos, licencias, zonas prohibidas y conservación. No fomenta pesca ilegal ni en lugares no autorizados.",
    articleExamples: ["Evaluación del agua", "Líneas y anzuelos", "Nudos de pesca", "Riesgos sanitarios", "Normativa y licencias"],
    usageTips: ["Verifica permisos y vedas.", "Evita consumir pescado de aguas dudosas."],
  },
  {
    id: "nudos-utiles",
    title: "Nudos útiles",
    description: "Nudos para campamento, sujeción, unión, carga y usos generales.",
    articleCountLabel: "19 nudos offline",
    expansion: "Incluye dificultad, usos y advertencias. No presenta nudos recreativos como sistemas profesionales de rescate si no corresponde.",
    articleExamples: ["As de guía", "Ballestrinque", "Nudo llano", "Nudo ocho", "Nudo camionero"],
    usageTips: ["Practica los nudos antes de necesitarlos.", "Respeta las advertencias de carga y uso profesional."],
  },
];
export const blogArticles = [
  "QuÃ© debe incluir una aplicaciÃ³n de supervivencia offline",
  "CÃ³mo prepararse para un apagÃ³n",
  "CÃ³mo crear un plan familiar de emergencia",
  "QuÃ© guardar en una mochila de 72 horas",
  "CÃ³mo utilizar mapas offline",
  "QuÃ© es un archivo MBTiles",
  "CÃ³mo ahorrar baterÃ­a durante una emergencia",
  "QuÃ© hacer cuando no hay cobertura",
  "CÃ³mo guardar agua para emergencias",
  "CÃ³mo preparar el coche para una averÃ­a",
  "QuÃ© hacer durante una DANA",
  "Diferencias entre alertas oficiales y avisos meteorolÃ³gicos",
  "CÃ³mo preparar a los niÃ±os sin asustarlos",
  "QuÃ© documentaciÃ³n conviene tener disponible",
  "CÃ³mo revisar un kit de emergencia",
];
