export const knotLibrary = [
  { id: "as-de-guia", name: "As de guía", group: "Lazos", purpose: "Reconocer la familia de lazos fijos al extremo de una cuerda.", limit: "No extrapoles un lazo de práctica a un arnés ni a la sujeción de personas. Las variantes y remates importan." },
  { id: "ballestrinque", name: "Ballestrinque", group: "Amarres", purpose: "Estudiar un amarre que puede regularse antes de cargarlo.", limit: "Puede deslizar o aflojarse según la cuerda, el soporte y la dirección de tracción. No es una autorización para cargas críticas." },
  { id: "nudo-ocho", name: "Nudo ocho", group: "Topes", purpose: "Distinguir el ocho simple de sus variantes con lazo y de encordamiento.", limit: "El ocho simple de tope no equivale a un ocho de encordamiento. No intercambies sus instrucciones." },
  { id: "prusik", name: "Prusik", group: "Técnicos", purpose: "Conocer qué es un nudo de fricción dentro de un sistema de cuerda.", limit: "Su comportamiento depende de diámetros, materiales y condiciones. Ascenso y rescate requieren formación y equipos específicos." },
  { id: "pescador-doble", name: "Pescador doble", group: "Uniones", purpose: "Estudiar una unión de extremos y diferenciarla de un amarre a un soporte.", limit: "Una unión no devuelve a una cuerda dañada su resistencia original. No la presentes como reparación para uso crítico." },
  { id: "vuelta-escota", name: "Vuelta de escota", group: "Uniones", purpose: "Reconocer una unión en la que un cabo rodea el seno del otro.", limit: "No es el nudo llano. La orientación, los materiales y las diferencias de diámetro condicionan el resultado." },
  { id: "nudo-tensor", name: "Nudo tensor", group: "Tensado", purpose: "Entender un ajuste de longitud en un viento ligero de campamento.", limit: "La cuerda lisa o las condiciones ambientales pueden alterar la fricción. No lo uses como sustituto de un sistema de rescate." },
  { id: "mariposa-alpina", name: "Mariposa alpina", group: "Lazos", purpose: "Reconocer un lazo situado en un tramo intermedio de cuerda.", limit: "La denominación no basta para comprobar una ejecución. Los usos técnicos exigen aprendizaje supervisado." },
  { id: "nudo-lenador", name: "Nudo leñador", group: "Amarres", purpose: "Diferenciar un amarre alrededor de un objeto de un lazo independiente.", limit: "No improvises izados ni arrastres con personas cerca. Esta ficha no calcula resistencia ni capacidad de carga." },
  { id: "nudo-llano", name: "Nudo llano", group: "Atados ligeros", purpose: "Practicar un atado alrededor de un paquete ligero.", limit: "No es una unión de seguridad entre cuerdas: puede volcarse y soltarse. No usar para personas ni cargas suspendidas." },
  { id: "vuelta-redonda-dos-cotes", name: "Vuelta redonda y dos cotes", group: "Amarres", purpose: "Estudiar por separado la vuelta alrededor del soporte y los dos cotes.", limit: "No deduzcas una carga admisible a partir del dibujo ni de que el nudo parezca apretado." },
  { id: "nudo-corredizo", name: "Nudo corredizo", group: "Lazos", purpose: "Comprender la diferencia entre un lazo regulable y uno fijo.", limit: "El lazo puede cerrarse al tirar. Nunca lo pongas alrededor del cuerpo, de una extremidad o de un animal." },
  { id: "nudo-alondra", name: "Nudo de alondra", group: "Amarres", purpose: "Reconocer una sujeción formada a partir de un seno.", limit: "La resistencia del conjunto no es la de la cuerda por sí sola. No trasladar un ejemplo decorativo a una maniobra técnica." },
  { id: "nudo-camionero", name: "Nudo de camionero", group: "Tensado", purpose: "Entender que algunos montajes combinan varios nudos para tensar.", limit: "Puede generar tensión elevada. No sustituye sistemas certificados de sujeción de carga en vehículos." },
  { id: "nudo-palomar", name: "Palomar", group: "Pesca", purpose: "Conocer una familia de unión de línea a un ojal.", limit: "Compatibilidad y ejecución dependen de la línea y del accesorio. Practica con un aro sin punta, no con un anzuelo expuesto." },
  { id: "clinch-mejorado", name: "Clinch mejorado", group: "Pesca", purpose: "Distinguir una unión de pesca de un nudo para cuerda de campamento.", limit: "No sirve cualquier receta para cualquier línea. Consulta la documentación del material y evita puntas durante la práctica." },
  { id: "nudo-simple-tope", name: "Nudo simple de tope", group: "Topes", purpose: "Reconocer un engrosamiento en el extremo de una cuerda.", limit: "No garantiza que la cuerda quede retenida en cualquier abertura ni habilita su uso en altura." },
  { id: "nudo-dinamico-munter", name: "Nudo dinámico / Munter", group: "Técnicos", purpose: "Distinguir un sistema de frenado de uno que bloquea por sí mismo.", limit: "No es un nudo autobloqueante. No se enseña aquí a asegurar, descender ni detener una caída." },
  { id: "amarre-cuadrado", name: "Amarre cuadrado", group: "Amarres", purpose: "Estudiar cómo se organizan vueltas para relacionar dos elementos.", limit: "Una maqueta no valida una estructura. No construir plataformas, refugios elevados ni soportes de personas con esta ficha." },
] as const;

export const plantLibrary = [
  {
    id: "ortiga-mayor", appId: "edible-1", name: "Ortiga mayor", scientificName: "Urtica dioica",
    image: "/images/from-app/ortiga-mayor.jpg",
    alt: "Imagen de ortiga mayor incluida en la aplicación; hojas dentadas y tallo visibles.",
    observation: "Fíjate en la disposición de las hojas y en su borde. Anota el entorno y fotografía el conjunto desde una distancia que evite el contacto.",
    limit: "No la manipules para comprobar su identidad. Un nombre o una imagen no autorizan a consumirla ni a preparar un remedio.",
    exercise: "Compara una vista general y otra de las hojas sin tocarlas. Si solo tienes una fotografía parcial, registra la observación como pendiente de identificación.",
    source: "https://www.kew.org/read-and-watch/identify-plants-street", sourceLabel: "Royal Botanic Gardens, Kew: plantas del entorno",
  },
  {
    id: "diente-de-leon", appId: "edible-2", name: "Diente de león", scientificName: "Taraxacum, grupo officinale",
    image: "/images/from-app/diente-de-leon.jpg",
    alt: "Imagen de diente de león de la aplicación, con capítulo amarillo y hojas basales.",
    observation: "Observa la planta completa, no solo la flor amarilla: hojas, disposición en la base y tallos aportan información distinta.",
    limit: "El nombre común abarca un grupo complejo. No identifiques una planta desconocida solo por el color de su flor ni decidas su consumo con esta ficha.",
    exercise: "Anota qué partes no aparecen en tu fotografía. Esa lista de información que falta es tan importante como el parecido con una imagen de referencia.",
    source: "https://www.kew.org/plants/dandelion", sourceLabel: "Royal Botanic Gardens, Kew: dandelion",
  },
  {
    id: "llanten-mayor", appId: "edible-5", name: "Llantén mayor", scientificName: "Plantago major",
    image: "/images/from-app/llanten-mayor.jpg",
    alt: "Imagen de llantén mayor de la aplicación, con hojas basales y espigas alargadas.",
    observation: "Compara forma y nervios de las hojas, su disposición en la base y las estructuras alargadas que se elevan sobre ellas.",
    limit: "Una vista puede ocultar caracteres importantes. La ficha no es una clave botánica completa ni una recomendación de uso medicinal.",
    exercise: "Prepara tres vistas sin arrancar la planta: entorno, conjunto y detalle visible de una hoja. Contrasta después la observación con una fuente botánica especializada.",
    source: "https://powo.science.kew.org/taxon/321286-2", sourceLabel: "Plants of the World Online: Plantago major",
  },
] as const;
