export const moreGroupSignals = [
  {id:"ven",name:"Ven / sígueme",gesture:"Palma hacia ti con un movimiento de atraer.",use:"Invitar a acercarse durante una práctica en un lugar conocido.",exercise:"Acordad primero el punto de reunión y probad el gesto a pocos pasos de distancia.",limit:"No indica que el camino esté libre de peligro ni que debas abandonar un lugar protegido."},
  {id:"reunirse",name:"Reagruparse",gesture:"Abrir los brazos y acercar las manos al pecho.",use:"Reunir al grupo antes de explicar una actividad o comprobar quién está presente.",exercise:"Elegid un punto visible y accesible. Confirmad que todos saben dónde reunirse.",limit:"Reunirse no significa que estén todos: hace falta comprobar cada persona y sus necesidades."},
  {id:"agua",name:"Agua",gesture:"Simular un vaso que se acerca a la boca.",use:"Expresar una necesidad de agua durante la práctica.",exercise:"Acordad si significa pedir agua o señalar dónde está; no uséis ambas interpretaciones sin aclaración.",limit:"La señal y las imágenes de pozos o ríos de la lámina no indican que el agua sea potable."},
  {id:"comida",name:"Comida",gesture:"Acercar los dedos juntos a la boca.",use:"Comunicar una necesidad o acordar una pausa para comer.",exercise:"Distinguid entre pedir comida y ofrecerla, confirmándolo con palabras.",limit:"No identifica alimentos seguros ni sustituye comprobar alergias, conservación y necesidades individuales."},
  {id:"contar",name:"Contar personas",gesture:"Mostrar con los dedos el número acordado y señalar a los miembros del grupo.",use:"Recordar que hay que comprobar quién está antes de comenzar una actividad.",exercise:"Haced una lista de participantes y contrastad nombres, no solo un número. No simuléis una desaparición sin avisar.",limit:"Un recuento numérico puede ocultar una confusión de personas. No iniciéis una búsqueda peligrosa como parte del ejercicio."},
  {id:"telefono",name:"Teléfono / mensaje",gesture:"Señalar el teléfono o llevar una mano a la oreja.",use:"Pedir que se use el medio de contacto que habéis acordado.",exercise:"Practicad con una llamada o mensaje a una persona que sabe que es un ejercicio.",limit:"No hagáis llamadas de prueba al 112. El gesto no especifica por sí solo a quién llamar ni qué comunicar."},
  {id:"linterna",name:"Luz / linterna",gesture:"Señalar los ojos y simular pulsar un botón.",use:"Pedir iluminación para una tarea sencilla, sin depender de que todos tengan la misma linterna.",exercise:"Acordad por separado qué significa encender, apagar o reducir la luz; la misma señal no debe ordenar las tres cosas.",limit:"No apuntéis a los ojos ni practiquéis destellos hacia vehículos. No es una señal de rescate normalizada."},
  {id:"no",name:"No / no pasar",gesture:"Cruzar los antebrazos delante del pecho.",use:"Rechazar una acción dentro del ejercicio acordado.",exercise:"Comprobad que todos entienden la negación y pueden pedir una explicación.",limit:"En caso de peligro, acompaña el aviso con un medio que la persona pueda percibir. No presupongas que ve el gesto."},
  {id:"ok",name:"Entendido",gesture:"Acordar un pulgar levantado o el gesto que el grupo pueda realizar.",use:"Confirmar que se ha recibido un mensaje sencillo.",exercise:"Pedid además que se repita el mensaje al aprender: confirmar recepción no siempre significa haber entendido bien.",limit:"No equivale a una valoración de salud, seguridad o estado del terreno. Los gestos cambian entre contextos y culturas."},
  {id:"lento",name:"Más despacio",gesture:"Palma hacia abajo con un movimiento lento y suave.",use:"Solicitar un ritmo de práctica que permita participar a todos.",exercise:"Probad el gesto estando quietos antes de usarlo en un paseo tranquilo.",limit:"Ir más despacio no convierte un paso peligroso en seguro. No practiquéis sobre escombros ni superficies resbaladizas."},
];
