import type { BlogPost } from './blog';
const common = { category: 'Naturaleza y preparación', date: '27 septiembre 2026', publishedAt: '2026-09-27', readingTime: '4 min', image: '/images/blog/aprendizaje-campo-natural.jpg', imageAlt: 'Observación del entorno en una salida. Imagen ilustrativa generada con IA.' };
export const outdoorArticles: BlogPost[] = [
  { ...common, slug: 'caza-observacion-fauna-preparacion', title: 'Caza y fauna: qué preparar antes de salir al campo', seoTitle: 'Caza, rastros y fauna: preparación y límites de seguridad', excerpt: 'Adapta las fichas de la app a una salida responsable: documentación, observación de rastros, regreso y límites que no conviene improvisar.', keywords: ['caza preparación', 'observación fauna', 'huellas y rastros'],
    warning: 'Una emergencia no convierte cualquier captura en legal o segura. Esta guía no enseña a montar trampas, usar armas ni decidir si una pieza es apta para consumo.',
    sections: [
      { heading: 'Antes de pensar en capturas, revisa tus prioridades', body: 'La app comienza por una idea útil: buscar alimento no debe empeorar una emergencia. En una salida planificada lleva comida suficiente y no cuentes con una captura como reserva garantizada. En una incidencia, prioriza evitar el peligro, comunicar tu situación y seguir las instrucciones de ayuda. Una actividad recreativa no sustituye un plan de regreso.' },
      { heading: 'Documentación y lugar: no hay un permiso universal', body: 'La regulación de la caza corresponde a las comunidades autónomas. Comprueba los requisitos de tu modalidad, territorio y temporada con el organismo competente. Una licencia no debe interpretarse como permiso para acceder a cualquier terreno o actuar sobre cualquier especie. Guarda la información aplicable antes de salir, con su fecha de consulta.' },
      { heading: 'Observar un rastro no es identificar con certeza', body: 'Barro, velocidad y huellas superpuestas alteran una pisada. Anota el entorno y fotografía desde un lugar seguro sin perseguir al animal. No publiques ubicaciones sensibles de fauna. Compara varios indicios con una guía especializada y conserva la incertidumbre: una imagen aislada no confirma una especie ni autoriza una actuación.' },
      { heading: 'Una ficha de campo sencilla', body: 'Adapta el registro de la app a un cuaderno. No hace falta acercarse a madrigueras ni manipular restos para completar una observación.', bullets: ['Fecha, entorno y condiciones del suelo.', 'Descripción de lo observado y posibles confusiones.', 'Referencia de tamaño solo si puedes obtenerla sin alterar el lugar.', 'Hora de regreso acordada y recurso para orientarte.', 'Motivo para detener la observación si cambia el tiempo o la seguridad.'] },
      { heading: 'No improvises la valoración sanitaria', body: 'No manipules animales enfermos o encontrados muertos. La apariencia no acredita que una pieza sea apta para consumo. Para una actividad autorizada, consulta los controles y requisitos sanitarios con los servicios competentes; no los sustituyas por una receta de Internet. Esta adaptación deja fuera las instrucciones de preparación y conservación de carne.' },
      { heading: 'Huellas: una lámina para observar y comparar', body: 'Material gráfico de la biblioteca de la app, sin su interfaz. La forma de una huella varía con el terreno y no confirma por sí sola una especie. Esta ilustración generada con IA no sustituye fotografías verificadas ni una guía especializada.', image: { src: '/images/blog/lamina-huella-jabali-app.jpg', alt: 'Lámina ilustrativa de la app sobre una huella atribuida a jabalí.', fullWidth: true, caption: 'Ilustración de huellas procedente de la app. No es una fotografía documental ni una identificación certificada. Pulsa para ampliar.' }, links: [{label:'Conocer la app',href:'/aplicacion-supervivencia-offline'}] },
    ], sources: [{ title: 'MAPA: competencias y coordinación en caza', url: 'https://www.mapa.gob.es/es/ganaderia/temas/gestion-cinegetica/comite_de_caza' }], relatedLinks: [{label:'Plantas y observación del entorno',href:'/plantas-y-fauna'},{label:'Preparar mapas antes de salir',href:'/preparacion-practica/mapas-antes-de-salir'}]
  },
  { ...common, slug: 'pesca-preparar-salida-responsable', title: 'Pesca: prepara la salida antes de acercarte al agua', seoTitle: 'Pesca responsable: equipo, preparación y seguridad de la salida', excerpt: 'Lugar, permisos, tiempo, material y regreso: una lista útil adaptada de la app, sin prometer capturas ni improvisar conservación.', keywords: ['pesca preparación', 'pesca responsable', 'seguridad orilla'],
    warning: 'Consulta la normativa y avisos del lugar. Esta guía no determina qué especies puedes capturar, qué artes están permitidas ni si un pescado es seguro para consumir.',
    sections: [
      { heading: 'La primera decisión ocurre antes de lanzar una línea', body: 'En la app, la evaluación del lugar precede al material. Ese orden evita convertir una salida en una búsqueda de capturas a cualquier precio. Revisa meteorología, acceso y regreso. No te acerques a una orilla inestable ni entres al agua para recuperar equipo. Lleva comida y agua sin depender del resultado de la pesca.' },
      { heading: 'Distingue aguas, modalidad y administración', body: 'La pesca marítima recreativa y la continental tienen requisitos diferentes. Consulta al organismo competente las licencias, permisos, zonas, temporadas, especies, tallas y límites de tu salida concreta. En el mar, la modalidad y las aguas también importan. Una tabla de la app o un artículo sin actualizar no sustituyen esa comprobación.' },
      { heading: 'Material pequeño y ordenado', body: 'Comprueba el estado del equipo siguiendo su manual. Guarda anzuelos y otros elementos punzantes de forma que no queden expuestos, especialmente cerca de menores y animales. Para aprender un nudo, practica antes en una mesa con un aro sin punta; no hace falta un anzuelo para ensayar los movimientos.', links: [{label:'Nudos por función',href:'/nudos'}] },
      { heading: 'Tu lista de comprobación antes de salir', body: 'Organiza una salida que puedas cancelar sin que falle tu abastecimiento. Una jornada sin capturas no es un fracaso ni una razón para asumir más riesgo.', bullets: ['Permisos y reglas del lugar consultados en una fuente oficial.', 'Previsión, avisos y ruta de acceso revisados.', 'Hora de regreso y contacto avisado del plan.', 'Iluminación propia, agua y alimento disponibles.', 'Bolsa para retirar líneas, envases y residuos sin abandonarlos.'] },
      { heading: 'No deduzcas seguridad alimentaria por el aspecto', body: 'Una fotografía no confirma la especie ni la aptitud del pescado. No improvises consumo en crudo, conservación o tratamiento frente a parásitos. Busca orientación sanitaria específica antes de planificar consumo. Las láminas ilustrativas de peces no se incluyen aquí como catálogo de identificación.' },
      { heading: 'Peces: material visual de la biblioteca', body: 'La lámina reúne imágenes rotuladas como lubina, dorada y caballa. Se reproduce como material ilustrativo de la app, no como validación de sus afirmaciones sobre captura o consumo: los permisos dependen del lugar y la fotografía no demuestra seguridad alimentaria.', image: {src:'/images/blog/lamina-peces-espana-app.jpg',alt:'Lámina de peces de la app con lubina, dorada y caballa.',fullWidth:true,caption:'Material ilustrativo de la app, no una autorización de pesca ni una guía sanitaria. Pulsa para ampliar.'}, links:[{label:'Conocer la app',href:'/aplicacion-supervivencia-offline'}] },
    ], sources: [{title:'MAPA: pesca marítima de recreo y preguntas frecuentes',url:'https://www.mapa.gob.es/es/pesca/temas/pesca-maritima-de-recreo/preguntas-frecuentes'}], relatedLinks:[{label:'Calendario lunar y sus límites',href:'/calendario-lunar'},{label:'Calcular las horas de luz',href:'/supervivencia/calculadora-horas-luz-ruta'}]
  },
];
outdoorArticles[0].image = '/images/blog/caza-observacion-editorial.jpg';
outdoorArticles[0].imageAlt = 'Prismáticos y cuaderno ante un paisaje con fauna distante. Portada generada con IA.';
outdoorArticles[1].image = '/images/blog/pesca-ribera-editorial.jpg';
outdoorArticles[1].imageAlt = 'Equipo de pesca preparado en una ribera. Portada generada con IA.';
